/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LEX_GFX (https://sketchfab.com/boltex360)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-bonfire-6c0ca6f74536435ab7d54eb17a1155bb
title: LowPoly bonfire
*/
// TODO: delete if unused
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/bonfire/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["lambert1.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/bonfire/scene.gltf");
