/* eslint-disable react/prop-types */
/* eslint-disable react/destructuring-assignment */
/* eslint-disable max-len */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mahdo (https://sketchfab.com/mahdo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crossy-road-b7e2910d0ffe4da5860dedf39a7131d1
title: Crossy Road
*/

import React, { Suspense, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

import Texts from "./Texts";

export default function Model({ ...props }) {
  // TODO: useLerp?
  const ref = useRef();

  const {
    position,
    direction,
    name,
  } = props;
  const { nodes, materials } = useGLTF("models/chicken/scene.gltf");

  const vec = new THREE.Vector3(...position);

  useFrame(() => {
    if (!ref.current) {
      return;
    }

    ref.current.position.lerp(vec, 0.05);
  });

  return (
    <group
      ref={ref}
    >
      <Suspense fallback={null}>
        <Texts position={[-23, 60, 0]} letters={name} />
      </Suspense>
      <group scale={[10, 10, 10]} rotation={[0, direction, 0]}>
        <group
          position={[0, 3.5, 0]}
          scale={[1.96, 3.02, 1.96]}
        >
          <mesh geometry={nodes.pCube1_phong5_0.geometry} material={materials.phong5} />
          <mesh geometry={nodes.pCube1_phong2_0.geometry} material={nodes.pCube1_phong2_0.material} />
          <mesh geometry={nodes.pCube1_phong3_0.geometry} material={materials.phong3} />
          <mesh geometry={nodes.pCube1_phong4_0.geometry} material={materials.phong4} />
        </group>
        <mesh
          position={[0, 0, 0]}
          geometry={nodes.pCube2_phong2_0.geometry}
          material={nodes.pCube2_phong2_0.material}
        />
        <mesh
          position={[1.5, 0, 0]}
          geometry={nodes.pCube2_phong2_0.geometry}
          material={nodes.pCube2_phong2_0.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/chicken/scene.gltf");
