/* eslint-disable react/prop-types */
/* eslint-disable react/destructuring-assignment */
/* eslint-disable max-len */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mahdo (https://sketchfab.com/mahdo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crossy-road-b7e2910d0ffe4da5860dedf39a7131d1
title: Crossy Road
*/

import React, { Suspense } from "react";
import { useGLTF } from "@react-three/drei";

import Texts from "./Texts";

export default function Model({ ...props }) {
  const { position, direction, name } = props;
  const { nodes, materials } = useGLTF("models/chicken/scene.gltf");

  return (
    <group
      position={[...position]}
    >
      <Suspense fallback={null}>
        <Texts position={[-7.65, 60, 0]} letters={name} />
      </Suspense>
      <group scale={[10, 10, 10]} rotation={[0, direction, 0]}>
        <group position={[-5.65, 3.67, 0]} scale={[1.96, 3.02, 1.96]}>
          <mesh geometry={nodes.pCube1_phong5_0.geometry} material={materials.phong5} />
          <mesh geometry={nodes.pCube1_phong2_0.geometry} material={nodes.pCube1_phong2_0.material} />
          <mesh geometry={nodes.pCube1_phong3_0.geometry} material={materials.phong3} />
          <mesh geometry={nodes.pCube1_phong4_0.geometry} material={materials.phong4} />
        </group>
        <mesh
          position={[-5.65, 0, 0]}
          geometry={nodes.pCube2_phong2_0.geometry}
          material={nodes.pCube2_phong2_0.material}
        />
        <mesh
          position={[-4.17, 0, 0]}
          geometry={nodes.pCube2_phong2_0.geometry}
          material={nodes.pCube2_phong2_0.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/chicken/scene.gltf");
