/* eslint-disable react/jsx-props-no-spreading */
/* eslint-disable max-len */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: media_mas (https://sketchfab.com/media_mas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/armario-lowpoly-1c19c1e1c38c4e1b84d6d420ac312cea
title: Armario - Lowpoly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/closet/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[12.03, -2.8, 152.15]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 2.8]}>
              <mesh geometry={nodes.armario_00_LP_madera_0.geometry} material={materials.madera} />
              <mesh geometry={nodes.armario_00_LP_vidrio_0.geometry} material={materials.vidrio} />
              <mesh geometry={nodes.armario_00_LP_oro_0.geometry} material={materials.material} />
              <mesh geometry={nodes.armario_00_LP_metal_oscuro_0.geometry} material={materials.metal_oscuro} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/closet/scene.gltf");
