/* eslint-disable max-len */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Onigraphics - Onigames (https://sketchfab.com/drop05)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-dungeon-game-props-c1d5eb92804f44d6b9cdf4b9f35cffc1
title: Lowpoly dungeon Game Props
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/dungeonProps/scene.gltf");
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[306.47, 14.69, 4.53]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[6.4, -1.22, 5.52]} scale={[0.92, 0.92, 0.92]}>
              <group position={[-6.49, 0, 0]}>
                <mesh
                  geometry={nodes["Object083_18_-_Default_0"].geometry}
                  material={nodes["Object083_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[-62.91, 0, 5.63]}>
              <mesh
                geometry={nodes["Object082_18_-_Default_0"].geometry}
                material={nodes["Object082_18_-_Default_0"].material}
              />
            </group>
          </group>
          <group position={[461.74, 52.15, -122.99]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.2, 0.35, -51.6]}>
              <group position={[24.67, 4.69, 49.43]}>
                <group position={[-17.58, -2.54, -3.88]}>
                  <group position={[-136.12, -2.15, 3.88]}>
                    <mesh
                      geometry={nodes["Object006_18_-_Default_0"].geometry}
                      material={nodes["Object006_18_-_Default_0"].material}
                    />
                  </group>
                </group>
                <group position={[-153.7, -4.69, 0]}>
                  <mesh
                    geometry={nodes["Object005_18_-_Default_0"].geometry}
                    material={nodes["Object005_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[-25, 4.74, 47.98]}>
                <group position={[17.7, -2.68, -2.75]}>
                  <group position={[2.61, -2.06, -1.18]}>
                    <mesh
                      geometry={nodes["Object007_18_-_Default_0"].geometry}
                      material={nodes["Object007_18_-_Default_0"].material}
                    />
                  </group>
                </group>
                <group position={[-104.03, -4.74, 1.46]}>
                  <mesh
                    geometry={nodes["Object002_18_-_Default_0"].geometry}
                    material={nodes["Object002_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[-129.03, 0, 49.43]}>
                <mesh
                  geometry={nodes["Object004_18_-_Default_0"].geometry}
                  material={nodes["Object004_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[-2.96, 14.75, -2.17]}>
              <group position={[0, -14.4, 0]}>
                <mesh
                  geometry={nodes["Object012_18_-_Default_0"].geometry}
                  material={nodes["Object012_18_-_Default_0"].material}
                />
              </group>
            </group>
          </group>
          <group
            position={[365.48, 44.24, -155.27]}
            rotation={[-1.03, 0, 0]}
            scale={[0.7, 0.7, 0.7]}
          >
            <group position={[-9.54, -0.39, -6.27]} rotation={[0, 0, 0]}>
              <group position={[5.99, -0.18, 5.53]} rotation={[0, 0, 0]}>
                <group position={[6.93, 0.18, 3.73]} rotation={[0, 0, 0]}>
                  <group position={[-264.64, 23, -19.52]}>
                    <mesh
                      geometry={nodes["Object030_18_-_Default_0"].geometry}
                      material={nodes["Object030_18_-_Default_0"].material}
                    />
                  </group>
                </group>
                <group position={[-257.71, 23.18, -15.79]}>
                  <mesh
                    geometry={nodes["Object031_18_-_Default_0"].geometry}
                    material={nodes["Object031_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[5.89, -0.36, -5.06]} rotation={[0, 0, 0]}>
                <group position={[18.79, 0, 0.27]} rotation={[0, 0, 0]}>
                  <group position={[0.23, -0.18, 11.49]} rotation={[0, 0, 0]}>
                    <group position={[-276.64, 23.54, -16.97]}>
                      <mesh
                        geometry={nodes["Object028_18_-_Default_0"].geometry}
                        material={nodes["Object028_18_-_Default_0"].material}
                      />
                    </group>
                  </group>
                  <group position={[-276.41, 23.36, -5.48]}>
                    <mesh
                      geometry={nodes["Object029_18_-_Default_0"].geometry}
                      material={nodes["Object029_18_-_Default_0"].material}
                    />
                  </group>
                </group>
                <group position={[-257.61, 23.36, -5.2]}>
                  <mesh
                    geometry={nodes["Object032_18_-_Default_0"].geometry}
                    material={nodes["Object032_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[3.31, -0.36, 0.69]} rotation={[0, 0, 0]}>
                <group position={[-255.03, 23.36, -10.96]}>
                  <mesh
                    geometry={nodes["Object026_18_-_Default_0"].geometry}
                    material={nodes["Object026_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[3.34, -0.36, 0.81]} rotation={[0, 0, 0]}>
                <group position={[-255.06, 23.36, -11.07]}>
                  <mesh
                    geometry={nodes["Object025_18_-_Default_0"].geometry}
                    material={nodes["Object025_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[3.59, -0.18, 0.73]} rotation={[0, 0, 0]}>
                <group position={[-255.31, 23.18, -10.99]}>
                  <mesh
                    geometry={nodes["Object027_18_-_Default_0"].geometry}
                    material={nodes["Object027_18_-_Default_0"].material}
                  />
                </group>
              </group>
              <group position={[-1.72, 23, -2.04]}>
                <mesh
                  geometry={nodes["Object024_18_-_Default_0"].geometry}
                  material={nodes["Object024_18_-_Default_0"].material}
                />
              </group>
            </group>
          </group>
          <group
            position={[204.21, 88.39, -208.61]}
            rotation={[0, -0.94, 0]}
            scale={[0.15, 0.15, 0.15]}
          >
            <group position={[2616.96, 108.17, -3980.88]}>
              <mesh geometry={nodes.chain1_estetic_props_0.geometry} material={nodes.chain1_estetic_props_0.material} />
            </group>
          </group>
          <group position={[299.09, -0.04, -37.42]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.7, 0.7, 0.7]}>
            <group position={[0, 7.89, 0]}>
              <mesh
                geometry={nodes.piedistallo_estetic_props_0.geometry}
                material={nodes.piedistallo_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[358.05, 0.82, -160.77]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.7, 0.7, 0.7]}>
            <group position={[0.31, 6.74, 2.78]}>
              <mesh geometry={nodes.leggio_estetic_props_0.geometry} material={nodes.leggio_estetic_props_0.material} />
            </group>
          </group>
          <group position={[213.27, 0.07, -30.54]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.53, 11.2, 0.67]}>
              <mesh
                geometry={nodes.Object043_estetic_props_0.geometry}
                material={nodes.Object043_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[187.66, -0.13, -28.47]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.73, 0.28, -2.25]}>
              <mesh
                geometry={nodes.Object045_estetic_props_0.geometry}
                material={nodes.Object045_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[150.49, -0.07, -22.51]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, 14.62]}>
              <mesh
                geometry={nodes.Object047_estetic_props_0.geometry}
                material={nodes.Object047_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[356.18, 66.13, -199.13]} rotation={[0, -0.94, 0]} scale={[0.12, 0.12, 0.12]}>
            <group position={[1133.1, 233.05, -1565.45]}>
              <mesh
                geometry={nodes.Object049_estetic_props_0.geometry}
                material={nodes.Object049_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[346.63, 0.05, -104.03]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.02, 6.1, 0]}>
              <mesh
                geometry={nodes.Object051_estetic_props_0.geometry}
                material={nodes.Object051_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[306.36, 20.1, -169.17]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[1283.47, 556.26, -1773.18]}>
              <mesh
                geometry={nodes.Object053_estetic_props_0.geometry}
                material={nodes.Object053_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[315.23, 65.62, -209.44]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[1910.12, 544.41, -2188.35]}>
              <mesh
                geometry={nodes.Object059_estetic_props_0.geometry}
                material={nodes.Object059_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[283.7, 66.52, -210.14]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2035.14, 538.5, -2353.25]}>
              <mesh
                geometry={nodes.Object061_estetic_props_0.geometry}
                material={nodes.Object061_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[295.41, 32.8, -209.24]} rotation={[0, 0, 0]}>
            <group position={[-0.24, -1.64, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                geometry={nodes.borchia_estetic_props_0.geometry}
                material={nodes.borchia_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[199.87, 0.3, -163.2]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2188.03, 686.2, -2833.74]}>
              <mesh geometry={nodes.barile_estetic_props_0.geometry} material={nodes.barile_estetic_props_0.material} />
            </group>
          </group>
          <group position={[235.07, -2.41, -86.06]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2209.1, 703.93, -3052]}>
              <mesh
                geometry={nodes.Object067_estetic_props_0.geometry}
                material={nodes.Object067_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[208.94, -0.6, -86.06]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2309.61, 692.11, -3190.87]}>
              <mesh
                geometry={nodes.Object069_estetic_props_0.geometry}
                material={nodes.Object069_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[196.55, -0.6, -86.06]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2423.99, 692.11, -3348.89]}>
              <mesh
                geometry={nodes.Object071_estetic_props_0.geometry}
                material={nodes.Object071_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[261.44, -4.62, 8.3]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2569.94, 718.43, -3550.52]}>
              <mesh
                geometry={nodes.candele1_estetic_props_0.geometry}
                material={nodes.candele1_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[252.84, 54.39, -211.34]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2717.47, 331.24, -3282.43]}>
              <mesh
                geometry={nodes.Object075_estetic_props_0.geometry}
                material={nodes.Object075_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[354.52, 114.09, -97.79]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.18, -0.92, -15.16]}>
              <group position={[16.2, 46.5, -15.63]}>
                <mesh
                  geometry={nodes.Object077_estetic_props_0.geometry}
                  material={nodes.Object077_estetic_props_0.material}
                />
              </group>
            </group>
            <group position={[0.02, -0.21, -9.22]}>
              <mesh
                geometry={nodes.Object034_estetic_props_0.geometry}
                material={nodes.Object034_estetic_props_0.material}
              />
            </group>
          </group>
          <group position={[389.58, 82.97, -204.29]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[16.2, 46.5, -15.63]}>
              <mesh geometry={nodes.chain2_estetic_props_0.geometry} material={nodes.chain2_estetic_props_0.material} />
            </group>
          </group>
          <group position={[436.55, 88.39, -214.7]} rotation={[0, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
            <group position={[2616.96, 108.17, -3980.88]}>
              <mesh geometry={nodes.chain3_estetic_props_0.geometry} material={nodes.chain3_estetic_props_0.material} />
            </group>
          </group>
          <group position={[240.13, -4.62, 8.3]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.candele2_estetic_props_0.geometry}
              material={nodes.candele2_estetic_props_0.material}
            />
          </group>
          <group position={[215.78, -4.62, 8.3]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.candela2_estetic_props_0.geometry}
              material={nodes.candela2_estetic_props_0.material}
            />
          </group>
          <group position={[219.15, -4.62, 8.3]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              geometry={nodes.candela1_estetic_props_0.geometry}
              material={nodes.candela1_estetic_props_0.material}
            />
          </group>
          <group position={[245.32, 13.41, -160.96]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.04, -8.42, 0.28]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-0.24, -1.64, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  geometry={nodes.Object081_estetic_props_0.geometry}
                  material={nodes.Object081_estetic_props_0.material}
                />
              </group>
            </group>
            <group position={[1.62, 0.18, -2.32]} rotation={[Math.PI / 2, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
              <group position={[1400.22, 615.37, -2024.35]}>
                <mesh
                  geometry={nodes.Object055_estetic_props_0.geometry}
                  material={nodes.Object055_estetic_props_0.material}
                />
              </group>
            </group>
          </group>
          <group position={[252.78, 9.23, -35.61]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-0.23, -4.32, 1.46]} rotation={[Math.PI / 2, 0, 0]}>
              <group position={[-0.24, -1.64, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                  geometry={nodes.Object080_estetic_props_0.geometry}
                  material={nodes.Object080_estetic_props_0.material}
                />
              </group>
            </group>
            <group position={[-2.29, 2.55, -9.85]} rotation={[Math.PI / 2, -0.94, 0]} scale={[0.15, 0.15, 0.15]}>
              <group position={[1560.64, 692.19, -2222.39]}>
                <mesh
                  geometry={nodes.Object057_estetic_props_0.geometry}
                  material={nodes.Object057_estetic_props_0.material}
                />
              </group>
            </group>
          </group>
          <group position={[284.78, 21.49, -102.55]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0.01, 6.81, -3.03]}>
              <group position={[-6.21, 0, 0]}>
                <mesh
                  geometry={nodes.Object041_estetic_props_0.geometry}
                  material={nodes.Object041_estetic_props_0.material}
                />
              </group>
            </group>
            <group position={[0, 9.77, -21.5]}>
              <group position={[-6.2, 0, 4.32]}>
                <mesh
                  geometry={nodes.Object040_estetic_props_0.geometry}
                  material={nodes.Object040_estetic_props_0.material}
                />
              </group>
            </group>
          </group>
          <group position={[160.46, 37.53, -190.24]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.7, 0.7, 0.7]}>
            <group position={[-13.66, 14.34, -1.73]} rotation={[0, 0, 0]}>
              <group position={[12.49, 5.19, 0.35]}>
                <mesh
                  geometry={nodes["Object044_18_-_Default_0"].geometry}
                  material={nodes["Object044_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[15.51, 14.29, 15.21]} rotation={[0, 0, 0]}>
              <group position={[-16.68, 5.24, -16.59]}>
                <mesh
                  geometry={nodes["Object040_18_-_Default_0"].geometry}
                  material={nodes["Object040_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[-1.16, 12.21, 27.53]} rotation={[0, 0, 0]}>
              <group position={[0, 0, -28.91]}>
                <mesh
                  geometry={nodes["Object041_18_-_Default_0"].geometry}
                  material={nodes["Object041_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[-3.05, 14.35, -1.73]} rotation={[0, 0, 0]}>
              <group position={[1.89, 5.18, 0.35]}>
                <mesh
                  geometry={nodes["Object042_18_-_Default_0"].geometry}
                  material={nodes["Object042_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[19.69, 6.7, -1.87]} rotation={[0, 0, 0]}>
              <group position={[-20.86, 12.82, 0.49]}>
                <mesh
                  geometry={nodes["Object039_18_-_Default_0"].geometry}
                  material={nodes["Object039_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group name="Object043" position={[6.34, 14.26, -1.91]}>
              <group position={[-7.5, 5.27, 0.53]}>
                <mesh
                  geometry={nodes["Object043_18_-_Default_0"].geometry}
                  material={nodes["Object043_18_-_Default_0"].material}
                />
              </group>
            </group>
            <group position={[-1.16, 19.53, -1.39]}>
              <mesh
                geometry={nodes["Object036_18_-_Default_0"].geometry}
                material={nodes["Object036_18_-_Default_0"].material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/dungeonProps/scene.gltf");
