/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hinger (https://sketchfab.com/hinger)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-school-grounds-6cb9a0b82e3a4d94994275f8e522b4fb
title: Low Poly School Grounds
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function FloatingIsland(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/floatingIsland/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <group position={[0, 0.04, 0]} rotation={[0, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group position={[0, 4.44, 2.04]} rotation={[-Math.PI / 2, 0, 0]} scale={[1000, 1000, 1000]}>
              <mesh geometry={nodes.Island_Material058_0.geometry} material={materials["Material.058"]} />
              <mesh geometry={nodes.Island_Material005_0.geometry} material={nodes.Island_Material005_0.material} />
              <mesh geometry={nodes.Island_Material001_0.geometry} material={nodes.Island_Material001_0.material} />
            </group>
            <group position={[190.7, 18.75, 87.5]} rotation={[1.52, 0.06, -0.82]} scale={[38.32, 1.42, 0.94]}>
              <mesh geometry={nodes.Cube012_Material013_0.geometry} material={nodes.Cube012_Material013_0.material} />
              <mesh geometry={nodes.Cube012_Material010_0.geometry} material={nodes.Cube012_Material010_0.material} />
            </group>
            <group position={[-35.4, 18.6, 1.77]} rotation={[1.58, -0.13, 1.67]} scale={[33.3, 1.63, 0.95]}>
              <mesh geometry={nodes.Cube013_Material013_0.geometry} material={nodes.Cube013_Material013_0.material} />
              <mesh geometry={nodes.Cube013_Material010_0.geometry} material={nodes.Cube013_Material010_0.material} />
            </group>
            <group position={[94.89, 46.29, 4.66]} rotation={[-Math.PI / 2, 0, 0]} scale={[27.82, 30.27, 36.97]}>
              <mesh geometry={nodes.Cylinder__0.geometry} material={nodes.Cylinder__0.material} />
            </group>
            <group position={[95.66, 94.42, 4.68]} rotation={[-Math.PI / 2, 0, 0]} scale={[10.39, 10.53, 12.36]}>
              <mesh geometry={nodes.Cylinder001__0.geometry} material={nodes.Cylinder001__0.material} />
            </group>
            <group position={[167.56, 6.13, -92.23]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.54, 9.21, 10.21]}>
              <mesh geometry={nodes.Torus001_Material015_0.geometry} material={nodes.Torus001_Material015_0.material} />
              <mesh geometry={nodes.Torus001_Bin_1_0.geometry} material={nodes.Torus001_Bin_1_0.material} />
              <mesh geometry={nodes.Torus001_Material001_0.geometry} material={nodes.Torus001_Material001_0.material} />
              <mesh geometry={nodes.Torus001_Material020_0.geometry} material={nodes.Torus001_Material020_0.material} />
              <mesh geometry={nodes.Torus001_Material019_0.geometry} material={nodes.Torus001_Material019_0.material} />
              <mesh geometry={nodes.Torus001_Material021_0.geometry} material={nodes.Torus001_Material021_0.material} />
            </group>
            <group position={[657.47, 56.16, -370.7]} rotation={[-Math.PI / 2, 0, 0]} scale={[42.76, 32.43, 54.33]}>
              <mesh geometry={nodes.Cube017_Material025_0.geometry} material={nodes.Cube017_Material025_0.material} />
              <mesh geometry={nodes.Cube017_Material024_0.geometry} material={nodes.Cube017_Material024_0.material} />
            </group>
            <group position={[602.37, 3.73, -110.34]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.54, 9.21, 10.21]}>
              <mesh geometry={nodes.Torus000_Material015_0.geometry} material={nodes.Torus000_Material015_0.material} />
              <mesh geometry={nodes.Torus000_Bin_1_0.geometry} material={nodes.Torus000_Bin_1_0.material} />
            </group>
            <group position={[710.19, 13.94, 188.23]} rotation={[-1.75, 0.15, -0.89]} scale={[5.16, 15.92, 16.18]}>
              <mesh geometry={nodes.Plane_Material019_0.geometry} material={nodes.Plane_Material019_0.material} />
              <mesh geometry={nodes.Plane_Material014_0.geometry} material={nodes.Plane_Material014_0.material} />
              <mesh geometry={nodes.Plane_Material005_0.geometry} material={nodes.Plane_Material005_0.material} />
            </group>
            <group position={[589.15, 22.64, 496.15]} rotation={[-Math.PI / 2, 0, 0]} scale={[42.76, 32.43, 54.33]}>
              <mesh geometry={nodes.Cube018_Material025_0.geometry} material={nodes.Cube018_Material025_0.material} />
              <mesh geometry={nodes.Cube018_Material024_0.geometry} material={nodes.Cube018_Material024_0.material} />
            </group>
            <group position={[704.78, 12.63, 218.06]} rotation={[-0.99, -0.11, 1.24]} scale={[25.85, 5.43, 26.09]}>
              <mesh geometry={nodes.Plane003_Material005_0.geometry} material={nodes.Plane003_Material005_0.material} />
              <mesh geometry={nodes.Plane003_Material007_0.geometry} material={materials["Material.007"]} />
            </group>
            <group position={[89.62, 2.44, -3.45]} rotation={[-Math.PI / 2, 0, 0]} scale={[201.02, 201.02, 1.71]}>
              <mesh
                geometry={nodes.Cylinder002_Material011_0.geometry}
                material={nodes.Cylinder002_Material011_0.material}
              />
            </group>
            <group position={[0, 31.52, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[1000, 1000, 1000]}>
              <mesh
                geometry={nodes.Island002_Material005_0.geometry}
                material={nodes.Island002_Material005_0.material}
              />
            </group>
            <group position={[507.63, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[251.22, 95.92, 6.32]}>
              <mesh geometry={nodes.Cube026_Material011_0.geometry} material={nodes.Cube026_Material011_0.material} />
            </group>
            <group position={[8.18, -2.15, 357.93]} rotation={[-Math.PI / 2, 0, 0.02]} scale={[70.22, 105.53, 2.12]}>
              <mesh geometry={nodes.Cube029_Material011_0.geometry} material={nodes.Cube029_Material011_0.material} />
            </group>
            <group position={[673.4, 7.43, 372.52]} rotation={[-1.41, -0.06, -0.16]} scale={[28.72, 38.41, 30.56]}>
              <mesh
                geometry={nodes.Icosphere001_Material006_0.geometry}
                material={nodes.Icosphere001_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere001_Material026_0.geometry}
                material={nodes.Icosphere001_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere001_Material003_0.geometry}
                material={nodes.Icosphere001_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere001_Material016_0.geometry}
                material={nodes.Icosphere001_Material016_0.material}
              />
            </group>
            <group position={[699.8, 3.23, -294.19]} rotation={[-1.63, 0.03, -3.09]} scale={[20.77, 27.78, 22.1]}>
              <mesh
                geometry={nodes.Icosphere000_Material006_0.geometry}
                material={nodes.Icosphere000_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere000_Material026_0.geometry}
                material={nodes.Icosphere000_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere000_Material003_0.geometry}
                material={nodes.Icosphere000_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere000_Material016_0.geometry}
                material={nodes.Icosphere000_Material016_0.material}
              />
            </group>
            <group position={[693.11, 6.96, -204.43]} rotation={[-1.77, 0.49, -0.82]} scale={[4.18, 12.89, 13.11]}>
              <mesh geometry={nodes.Plane001_Material019_0.geometry} material={nodes.Plane001_Material019_0.material} />
              <mesh geometry={nodes.Plane001_Material014_0.geometry} material={nodes.Plane001_Material014_0.material} />
              <mesh geometry={nodes.Plane001_Material005_0.geometry} material={nodes.Plane001_Material005_0.material} />
            </group>
            <group position={[699.09, 8.3, -170.35]} rotation={[-1.8, 0.69, -0.77]} scale={[6.7, 20.68, 21.03]}>
              <mesh geometry={nodes.Plane004_Material019_0.geometry} material={nodes.Plane004_Material019_0.material} />
              <mesh geometry={nodes.Plane004_Material014_0.geometry} material={nodes.Plane004_Material014_0.material} />
              <mesh geometry={nodes.Plane004_Material005_0.geometry} material={nodes.Plane004_Material005_0.material} />
            </group>
            <group position={[710.6, 33.85, 180.77]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.13, 0.13, 0.13]}>
              <mesh
                geometry={nodes.Icosphere004_Material010_0.geometry}
                material={nodes.Icosphere004_Material010_0.material}
              />
              <mesh
                geometry={nodes.Icosphere004_Material011_0.geometry}
                material={nodes.Icosphere004_Material011_0.material}
              />
              <mesh geometry={nodes.Icosphere004_Material030_0.geometry} material={materials["Material.030"]} />
              <mesh geometry={nodes.Icosphere004_Material012_0.geometry} material={materials["Material.012"]} />
            </group>
            <group position={[-197.67, -0.92, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[80.94, 100, 1.05]}>
              <mesh geometry={nodes.Cube035_Material011_0.geometry} material={nodes.Cube035_Material011_0.material} />
            </group>
            <group position={[-488.77, 18.75, 253.21]} rotation={[-1.54, 0.04, 3.1]} scale={[17.54, 28.84, 21.93]}>
              <mesh
                geometry={nodes.Icosphere003_Material006_0.geometry}
                material={nodes.Icosphere003_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere003_Material026_0.geometry}
                material={nodes.Icosphere003_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere003_Material003_0.geometry}
                material={nodes.Icosphere003_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere003_Material016_0.geometry}
                material={nodes.Icosphere003_Material016_0.material}
              />
            </group>
            <group
              position={[-595.59, 83.89, -424.64]}
              rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
              scale={[2.02, 44.05, 28.57]}
            >
              <mesh geometry={nodes.Cube103_Material009_0.geometry} material={nodes.Cube103_Material009_0.material} />
            </group>
            <group
              position={[-623.48, 83.31, -427.79]}
              rotation={[Math.PI / 2, 0.01, -Math.PI / 2]}
              scale={[0.35, 12.57, 25.79]}
            >
              <mesh geometry={nodes.Cube104_Material032_0.geometry} material={nodes.Cube104_Material032_0.material} />
              <mesh geometry={nodes.Cube104_Material033_0.geometry} material={nodes.Cube104_Material033_0.material} />
            </group>
            <group position={[-593.85, 84.06, -420.94]} rotation={[-1.57, 1.57, 1.57]} scale={[4.7, 26.26, 39.41]}>
              <mesh geometry={nodes.Cube105_Material031_0.geometry} material={nodes.Cube105_Material031_0.material} />
            </group>
            <group position={[-366.15, 2.93, -198.29]} rotation={[-Math.PI / 2, 0, 0]} scale={[9.54, 9.21, 10.21]}>
              <mesh geometry={nodes.Torus003_Material015_0.geometry} material={nodes.Torus003_Material015_0.material} />
              <mesh geometry={nodes.Torus003_Bin_1_0.geometry} material={nodes.Torus003_Bin_1_0.material} />
              <mesh geometry={nodes.Torus003_Material001_0.geometry} material={nodes.Torus003_Material001_0.material} />
              <mesh geometry={nodes.Torus003_Material020_0.geometry} material={nodes.Torus003_Material020_0.material} />
              <mesh geometry={nodes.Torus003_Material019_0.geometry} material={nodes.Torus003_Material019_0.material} />
              <mesh geometry={nodes.Torus003_Material021_0.geometry} material={nodes.Torus003_Material021_0.material} />
            </group>
            <group position={[663.41, 62.54, -222.95]} rotation={[-Math.PI / 2, 0, 0]} scale={[42.76, 32.43, 54.33]}>
              <mesh geometry={nodes.Cube106_Material038_0.geometry} material={nodes.Cube106_Material038_0.material} />
              <mesh geometry={nodes.Cube106_Material039_0.geometry} material={materials["Material.039"]} />
            </group>
            <group position={[659.29, 14.29, 183.9]} rotation={[-1.62, 0, -Math.PI]} scale={[42.76, 32.43, 54.33]}>
              <mesh geometry={nodes.Cube107_Material040_0.geometry} material={nodes.Cube107_Material040_0.material} />
              <mesh geometry={nodes.Cube107_Material041_0.geometry} material={nodes.Cube107_Material041_0.material} />
            </group>
            <group position={[589.15, 22.64, 496.15]} rotation={[-Math.PI / 2, 0, 0]} scale={[42.76, 32.43, 54.33]}>
              <mesh geometry={nodes.Cube014_Material040_0.geometry} material={nodes.Cube014_Material040_0.material} />
              <mesh geometry={nodes.Cube014_Material041_0.geometry} material={nodes.Cube014_Material041_0.material} />
            </group>
            <group position={[611.14, 28.92, -247]} rotation={[-1.63, 0.03, -3.09]} scale={[25.98, 34.75, 27.64]}>
              <mesh
                geometry={nodes.Icosphere005_Material006_0.geometry}
                material={nodes.Icosphere005_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere005_Material026_0.geometry}
                material={nodes.Icosphere005_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere005_Material003_0.geometry}
                material={nodes.Icosphere005_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere005_Material016_0.geometry}
                material={nodes.Icosphere005_Material016_0.material}
              />
            </group>
            <group position={[620.12, 28.92, 213.89]} rotation={[-1.5, -0.05, 0.07]} scale={[18.59, 24.86, 19.78]}>
              <mesh
                geometry={nodes.Icosphere006_Material006_0.geometry}
                material={nodes.Icosphere006_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere006_Material026_0.geometry}
                material={nodes.Icosphere006_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere006_Material003_0.geometry}
                material={nodes.Icosphere006_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere006_Material016_0.geometry}
                material={nodes.Icosphere006_Material016_0.material}
              />
            </group>
            <group position={[608.98, 26.34, 318.19]} rotation={[-1.62, 0.06, 2.97]} scale={[22.75, 30.43, 24.21]}>
              <mesh
                geometry={nodes.Icosphere007_Material006_0.geometry}
                material={nodes.Icosphere007_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere007_Material026_0.geometry}
                material={nodes.Icosphere007_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere007_Material003_0.geometry}
                material={nodes.Icosphere007_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere007_Material016_0.geometry}
                material={nodes.Icosphere007_Material016_0.material}
              />
            </group>
            <group position={[-493.47, 3.1, 351.94]} rotation={[-1, -0.32, -0.39]} scale={[0.82, 0.64, 7.86]}>
              <mesh
                geometry={nodes.Cylinder009_Material006_0.geometry}
                material={nodes.Cylinder009_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder009_Material042_0.geometry}
                material={nodes.Cylinder009_Material042_0.material}
              />
            </group>
            <group position={[-501.8, 5.49, 347.06]} rotation={[-1.69, 0.07, 0]} scale={[0.81, 0.63, 7.79]}>
              <mesh
                geometry={nodes.Cylinder010_Material006_0.geometry}
                material={nodes.Cylinder010_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder010_Material042_0.geometry}
                material={nodes.Cylinder010_Material042_0.material}
              />
            </group>
            <group position={[-486.82, 31.36, 223.07]} rotation={[-2.3, 0.69, 0]} scale={[0.57, 0.44, 5.44]}>
              <mesh
                geometry={nodes.Cylinder012_Material006_0.geometry}
                material={nodes.Cylinder012_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder012_Material042_0.geometry}
                material={nodes.Cylinder012_Material042_0.material}
              />
            </group>
            <group position={[-481.82, 5.97, 331.95]} rotation={[-1.25, -0.45, 0.51]} scale={[0.81, 0.63, 7.79]}>
              <mesh
                geometry={nodes.Cylinder013_Material006_0.geometry}
                material={nodes.Cylinder013_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder013_Material042_0.geometry}
                material={nodes.Cylinder013_Material042_0.material}
              />
            </group>
            <group position={[-494.57, 5.62, 336.19]} rotation={[-Math.PI / 2, -0.03, 0]} scale={[0.81, 0.63, 7.79]}>
              <mesh
                geometry={nodes.Cylinder014_Material006_0.geometry}
                material={nodes.Cylinder014_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder014_Material042_0.geometry}
                material={nodes.Cylinder014_Material042_0.material}
              />
            </group>
            <group position={[-480.49, 7.44, 326.15]} rotation={[-1.44, 0.2, -0.1]} scale={[0.81, 0.63, 7.79]}>
              <mesh
                geometry={nodes.Cylinder015_Material006_0.geometry}
                material={nodes.Cylinder015_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder015_Material042_0.geometry}
                material={nodes.Cylinder015_Material042_0.material}
              />
            </group>
            <group position={[-486.85, 7.9, 342.98]} rotation={[-1.85, 0.06, 1.28]} scale={[0.81, 0.63, 7.79]}>
              <mesh
                geometry={nodes.Cylinder016_Material006_0.geometry}
                material={nodes.Cylinder016_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder016_Material042_0.geometry}
                material={nodes.Cylinder016_Material042_0.material}
              />
            </group>
            <group position={[-481.53, 3.5, 351.92]} rotation={[-Math.PI / 2, 0.11, 0]} scale={[0.56, 0.44, 5.39]}>
              <mesh
                geometry={nodes.Cylinder017_Material006_0.geometry}
                material={nodes.Cylinder017_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder017_Material042_0.geometry}
                material={nodes.Cylinder017_Material042_0.material}
              />
            </group>
            <group position={[-503.75, 0.8, 355.21]} rotation={[-1.55, -0.11, -2.96]} scale={[0.77, 0.63, 7.78]}>
              <mesh
                geometry={nodes.Cylinder023_Material006_0.geometry}
                material={nodes.Cylinder023_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder023_Material042_0.geometry}
                material={nodes.Cylinder023_Material042_0.material}
              />
            </group>
            <group position={[689.88, 14.31, 238.44]} rotation={[-1.55, -0.11, -2.96]} scale={[0.77, 0.63, 7.86]}>
              <mesh
                geometry={nodes.Cylinder018_Material006_0.geometry}
                material={nodes.Cylinder018_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder018_Material042_0.geometry}
                material={nodes.Cylinder018_Material042_0.material}
              />
            </group>
            <group position={[-488.15, 8.57, 403.62]} rotation={[-1.28, -0.12, 2.85]} scale={[6.63, 20.48, 20.83]}>
              <mesh geometry={nodes.Plane005_Material019_0.geometry} material={nodes.Plane005_Material019_0.material} />
              <mesh geometry={nodes.Plane005_Material014_0.geometry} material={nodes.Plane005_Material014_0.material} />
              <mesh geometry={nodes.Plane005_Material005_0.geometry} material={nodes.Plane005_Material005_0.material} />
            </group>
            <group position={[-599.75, 21.49, 442.88]} rotation={[-1.53, -0.03, 1.53]} scale={[22.5, 23.99, 28.15]}>
              <mesh
                geometry={nodes.Icosphere008_Material006_0.geometry}
                material={nodes.Icosphere008_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere008_Material026_0.geometry}
                material={nodes.Icosphere008_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere008_Material003_0.geometry}
                material={nodes.Icosphere008_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere008_Material016_0.geometry}
                material={nodes.Icosphere008_Material016_0.material}
              />
            </group>
            <group position={[696.35, 11.47, -203.62]} rotation={[-Math.PI / 2, 0, -0.79]} scale={[1.8, 1.71, 2.12]}>
              <mesh
                geometry={nodes.Icosphere009_Material028_0.geometry}
                material={nodes.Icosphere009_Material028_0.material}
              />
              <mesh
                geometry={nodes.Icosphere009_Material027_0.geometry}
                material={nodes.Icosphere009_Material027_0.material}
              />
              <mesh
                geometry={nodes.Icosphere009_Material016_0.geometry}
                material={nodes.Icosphere009_Material016_0.material}
              />
              <mesh
                geometry={nodes.Icosphere009_Material008_0.geometry}
                material={nodes.Icosphere009_Material008_0.material}
              />
              <mesh
                geometry={nodes.Icosphere009_Material006_0.geometry}
                material={nodes.Icosphere009_Material006_0.material}
              />
            </group>
            <group position={[712.15, 30.02, 189.7]} rotation={[-Math.PI / 2, 0, -2.18]} scale={[3.3, 3.14, 3.89]}>
              <mesh
                geometry={nodes.Icosphere010_Material028_0.geometry}
                material={nodes.Icosphere010_Material028_0.material}
              />
              <mesh
                geometry={nodes.Icosphere010_Material027_0.geometry}
                material={nodes.Icosphere010_Material027_0.material}
              />
              <mesh
                geometry={nodes.Icosphere010_Material016_0.geometry}
                material={nodes.Icosphere010_Material016_0.material}
              />
              <mesh
                geometry={nodes.Icosphere010_Material008_0.geometry}
                material={nodes.Icosphere010_Material008_0.material}
              />
              <mesh
                geometry={nodes.Icosphere010_Material006_0.geometry}
                material={nodes.Icosphere010_Material006_0.material}
              />
            </group>
            <group position={[-519.28, 50.2, 511.4]} rotation={[-1.63, 0, 0]} scale={[12.39, 9.75, 29.21]}>
              <mesh
                geometry={nodes.Cylinder003_Material002_0.geometry}
                material={nodes.Cylinder003_Material002_0.material}
              />
              <mesh
                geometry={nodes.Cylinder003_Material047_0.geometry}
                material={nodes.Cylinder003_Material047_0.material}
              />
            </group>
            <group position={[-459, 22.1, 583.37]} rotation={[-1.55, -0.13, 1.95]} scale={[9.36, 7.37, 22.08]}>
              <mesh
                geometry={nodes.Cylinder011_Material002_0.geometry}
                material={nodes.Cylinder011_Material002_0.material}
              />
              <mesh
                geometry={nodes.Cylinder011_Material047_0.geometry}
                material={nodes.Cylinder011_Material047_0.material}
              />
            </group>
            <group position={[-673.76, -12.7, -479.46]} rotation={[-1.61, -0.11, -1.32]} scale={[11.81, 9.3, 32.7]}>
              <mesh
                geometry={nodes.Cylinder019_Material002_0.geometry}
                material={nodes.Cylinder019_Material002_0.material}
              />
              <mesh
                geometry={nodes.Cylinder019_Material047_0.geometry}
                material={nodes.Cylinder019_Material047_0.material}
              />
            </group>
            <group position={[-491.46, 6.86, -440.19]} rotation={[-1.75, 0.04, -0.76]} scale={[7.26, 22.41, 22.79]}>
              <mesh geometry={nodes.Plane006_Material019_0.geometry} material={nodes.Plane006_Material019_0.material} />
              <mesh geometry={nodes.Plane006_Material014_0.geometry} material={nodes.Plane006_Material014_0.material} />
              <mesh geometry={nodes.Plane006_Material005_0.geometry} material={nodes.Plane006_Material005_0.material} />
            </group>
            <group position={[-486.63, 10.13, -405.66]} rotation={[-1.54, -0.01, -1.72]} scale={[5.72, 17.65, 17.95]}>
              <mesh geometry={nodes.Plane007_Material019_0.geometry} material={nodes.Plane007_Material019_0.material} />
              <mesh geometry={nodes.Plane007_Material014_0.geometry} material={nodes.Plane007_Material014_0.material} />
              <mesh geometry={nodes.Plane007_Material005_0.geometry} material={nodes.Plane007_Material005_0.material} />
            </group>
            <group position={[-529.79, -2.39, -451.72]} rotation={[-1.36, 0.11, -2.45]} scale={[4.1, 12.66, 12.87]}>
              <mesh geometry={nodes.Plane008_Material019_0.geometry} material={nodes.Plane008_Material019_0.material} />
              <mesh geometry={nodes.Plane008_Material014_0.geometry} material={nodes.Plane008_Material014_0.material} />
              <mesh geometry={nodes.Plane008_Material005_0.geometry} material={nodes.Plane008_Material005_0.material} />
            </group>
            <group position={[-505.1, 3.21, -393.37]} rotation={[-1.54, -0.1, -2.81]} scale={[0.84, 0.69, 8.52]}>
              <mesh
                geometry={nodes.Cylinder020_Material006_0.geometry}
                material={nodes.Cylinder020_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder020_Material042_0.geometry}
                material={nodes.Cylinder020_Material042_0.material}
              />
            </group>
            <group position={[-481.41, 3.21, -346.76]} rotation={[-1.64, 0.09, 0.63]} scale={[0.84, 0.69, 8.52]}>
              <mesh
                geometry={nodes.Cylinder021_Material006_0.geometry}
                material={nodes.Cylinder021_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder021_Material042_0.geometry}
                material={nodes.Cylinder021_Material042_0.material}
              />
            </group>
            <group position={[-486.75, 10.14, -331.36]} rotation={[-1.36, 0.11, -2.45]} scale={[4.1, 12.66, 12.87]}>
              <mesh geometry={nodes.Plane009_Material019_0.geometry} material={nodes.Plane009_Material019_0.material} />
              <mesh geometry={nodes.Plane009_Material014_0.geometry} material={nodes.Plane009_Material014_0.material} />
              <mesh geometry={nodes.Plane009_Material005_0.geometry} material={nodes.Plane009_Material005_0.material} />
            </group>
            <group position={[-487.39, 19.84, -256.3]} rotation={[-1.63, 0.03, -3.09]} scale={[20.77, 27.78, 22.1]}>
              <mesh
                geometry={nodes.Icosphere012_Material006_0.geometry}
                material={nodes.Icosphere012_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere012_Material026_0.geometry}
                material={nodes.Icosphere012_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere012_Material003_0.geometry}
                material={nodes.Icosphere012_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere012_Material016_0.geometry}
                material={nodes.Icosphere012_Material016_0.material}
              />
            </group>
            <group position={[648.67, 81.5, 57.87]} rotation={[-Math.PI / 2, 0, 2.09]} scale={[45.94, 1.9, 70.87]}>
              <mesh geometry={nodes.Cube015_Material049_0.geometry} material={nodes.Cube015_Material049_0.material} />
            </group>
            <group position={[625.85, 79.6, -77.8]} rotation={[-Math.PI / 2, 0, -2.94]} scale={[45.34, 1.88, 71.55]}>
              <mesh geometry={nodes.Cube038_Material049_0.geometry} material={nodes.Cube038_Material049_0.material} />
            </group>
            <group
              position={[355.91, 70.09, -396.04]}
              rotation={[-Math.PI / 2, -0.05, 0.87]}
              scale={[57.58, 43.2, 69.08]}
            >
              <mesh geometry={nodes.Cube057_Material053_0.geometry} material={materials["Material.053"]} />
              <mesh geometry={nodes.Cube057_Material055_0.geometry} material={materials["Material.055"]} />
              <mesh geometry={nodes.Cube057_Material054_0.geometry} material={materials["Material.054"]} />
              <mesh geometry={nodes.Cube057_Material051_0.geometry} material={materials["Material.051"]} />
              <mesh geometry={nodes.Cube057_Material032_0.geometry} material={nodes.Cube057_Material032_0.material} />
              <mesh geometry={nodes.Cube057_Material004_0.geometry} material={nodes.Cube057_Material004_0.material} />
            </group>
            <group position={[353.26, 19.29, -517.15]} rotation={[-1.57, 0, -1.31]} scale={[10.22, 8.05, 28.29]}>
              <mesh
                geometry={nodes.Cylinder022_Material002_0.geometry}
                material={nodes.Cylinder022_Material002_0.material}
              />
              <mesh
                geometry={nodes.Cylinder022_Material047_0.geometry}
                material={nodes.Cylinder022_Material047_0.material}
              />
            </group>
            <group position={[265.99, 36.29, -502.2]} rotation={[-1.54, 0, -1.31]} scale={[7.78, 6.13, 21.54]}>
              <mesh
                geometry={nodes.Cylinder024_Material002_0.geometry}
                material={nodes.Cylinder024_Material002_0.material}
              />
              <mesh
                geometry={nodes.Cylinder024_Material047_0.geometry}
                material={nodes.Cylinder024_Material047_0.material}
              />
            </group>
            <group position={[374.04, 17.26, -317.74]} rotation={[-1.54, 0.31, -1.81]} scale={[5, 15.44, 15.7]}>
              <mesh geometry={nodes.Plane010_Material019_0.geometry} material={nodes.Plane010_Material019_0.material} />
              <mesh geometry={nodes.Plane010_Material014_0.geometry} material={nodes.Plane010_Material014_0.material} />
              <mesh geometry={nodes.Plane010_Material005_0.geometry} material={nodes.Plane010_Material005_0.material} />
            </group>
            <group position={[279.99, 4.52, -377.95]} rotation={[-1.69, 0.11, 0.03]} scale={[0.77, 0.63, 7.86]}>
              <mesh
                geometry={nodes.Cylinder025_Material006_0.geometry}
                material={nodes.Cylinder025_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder025_Material042_0.geometry}
                material={nodes.Cylinder025_Material042_0.material}
              />
            </group>
            <group position={[374.98, 22.37, -313.55]} rotation={[-1.43, -0.03, -1.65]} scale={[2.16, 2.06, 2.55]}>
              <mesh
                geometry={nodes.Icosphere014_Material028_0.geometry}
                material={nodes.Icosphere014_Material028_0.material}
              />
              <mesh
                geometry={nodes.Icosphere014_Material027_0.geometry}
                material={nodes.Icosphere014_Material027_0.material}
              />
              <mesh
                geometry={nodes.Icosphere014_Material016_0.geometry}
                material={nodes.Icosphere014_Material016_0.material}
              />
              <mesh
                geometry={nodes.Icosphere014_Material008_0.geometry}
                material={nodes.Icosphere014_Material008_0.material}
              />
              <mesh
                geometry={nodes.Icosphere014_Material006_0.geometry}
                material={nodes.Icosphere014_Material006_0.material}
              />
            </group>
            <group position={[-232.61, 15.66, -421.92]} rotation={[-1.58, -0.11, 3.1]} scale={[0.77, 0.63, 7.86]}>
              <mesh
                geometry={nodes.Cylinder026_Material006_0.geometry}
                material={nodes.Cylinder026_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder026_Material042_0.geometry}
                material={nodes.Cylinder026_Material042_0.material}
              />
            </group>
            <group position={[305.82, 2.27, 687.59]} rotation={[-1.62, -0.05, -1.82]} scale={[20.27, 20.35, 20.62]}>
              <mesh
                geometry={nodes.Icosphere013_Material006_0.geometry}
                material={nodes.Icosphere013_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere013_Material026_0.geometry}
                material={nodes.Icosphere013_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere013_Material003_0.geometry}
                material={nodes.Icosphere013_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere013_Material016_0.geometry}
                material={nodes.Icosphere013_Material016_0.material}
              />
            </group>
            <group position={[286.02, -1.35, 656.71]} rotation={[-1.48, 0.06, -1.02]} scale={[0.67, 0.55, 6.8]}>
              <mesh
                geometry={nodes.Cylinder027_Material006_0.geometry}
                material={nodes.Cylinder027_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder027_Material042_0.geometry}
                material={nodes.Cylinder027_Material042_0.material}
              />
            </group>
            <group position={[314.48, -4.6, 661.46]} rotation={[-1.49, 0.08, -0.79]} scale={[0.71, 0.58, 7.23]}>
              <mesh
                geometry={nodes.Cylinder028_Material006_0.geometry}
                material={nodes.Cylinder028_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder028_Material042_0.geometry}
                material={nodes.Cylinder028_Material042_0.material}
              />
            </group>
            <group position={[324.74, -4.6, 670.86]} rotation={[-1.52, 0.1, -0.51]} scale={[0.71, 0.58, 7.23]}>
              <mesh
                geometry={nodes.Cylinder029_Material006_0.geometry}
                material={nodes.Cylinder029_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder029_Material042_0.geometry}
                material={nodes.Cylinder029_Material042_0.material}
              />
            </group>
            <group position={[388.55, -2.81, 679.04]} rotation={[-1.8, 0.06, -1.1]} scale={[19.98, 17.32, 20.59]}>
              <mesh
                geometry={nodes.Icosphere015_Material006_0.geometry}
                material={nodes.Icosphere015_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere015_Material026_0.geometry}
                material={nodes.Icosphere015_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere015_Material003_0.geometry}
                material={nodes.Icosphere015_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere015_Material016_0.geometry}
                material={nodes.Icosphere015_Material016_0.material}
              />
            </group>
            <group position={[-661.92, 309.36, -199.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.95, 13.75, 38.17]}>
              <mesh geometry={nodes.Cube033_Material031_0.geometry} material={nodes.Cube033_Material031_0.material} />
              <mesh geometry={nodes.Cube033_Material015_0.geometry} material={nodes.Cube033_Material015_0.material} />
            </group>
            <group position={[-629.6, 309.36, -199.14]} rotation={[-Math.PI / 2, 0, 0]} scale={[16.95, 13.75, 38.17]}>
              <mesh geometry={nodes.Cube034_Material031_0.geometry} material={nodes.Cube034_Material031_0.material} />
              <mesh geometry={nodes.Cube034_Material015_0.geometry} material={nodes.Cube034_Material015_0.material} />
            </group>
            <group position={[-398.31, -318.37, 795.98]} rotation={[0.09, -0.5, 0.04]} scale={[66.15, 63.07, 63.07]}>
              <mesh
                geometry={nodes.Cylinder030_Material015_0.geometry}
                material={nodes.Cylinder030_Material015_0.material}
              />
            </group>
            <group position={[-409.38, -318.37, 816.3]} rotation={[0.09, -0.5, 0.04]} scale={[49.07, 46.65, 17.7]}>
              <mesh
                geometry={nodes.Cylinder031_Material015_0.geometry}
                material={nodes.Cylinder031_Material015_0.material}
              />
            </group>
            <group position={[16.66, -295.72, -857.23]} rotation={[3.06, -0.05, 3.14]} scale={[55.83, 53.23, 53.23]}>
              <mesh
                geometry={nodes.Cylinder032_Material015_0.geometry}
                material={nodes.Cylinder032_Material015_0.material}
              />
            </group>
            <group position={[14.88, -295.72, -898.13]} rotation={[3.06, -0.05, 3.14]} scale={[41.41, 39.37, 14.94]}>
              <mesh
                geometry={nodes.Cylinder033_Material015_0.geometry}
                material={nodes.Cylinder033_Material015_0.material}
              />
            </group>
            <group position={[121, -242.51, -867.89]} rotation={[3.06, 0.09, -3.13]} scale={[31.01, 29.57, 29.57]}>
              <mesh
                geometry={nodes.Cylinder034_Material015_0.geometry}
                material={nodes.Cylinder034_Material015_0.material}
              />
            </group>
            <group position={[-783.14, -3.62, 5.54]} rotation={[-Math.PI / 2, 0, -3.1]} scale={[-5.08, 57.2, 4.77]}>
              <mesh geometry={nodes.Cube000_Marble_0.geometry} material={nodes.Cube000_Marble_0.material} />
            </group>
            <group position={[-740.39, 7.37, -69.73]} rotation={[-1.68, 0.01, 1.47]} scale={[0.84, 0.69, 8.52]}>
              <mesh
                geometry={nodes.Cylinder036_Material006_0.geometry}
                material={nodes.Cylinder036_Material006_0.material}
              />
              <mesh
                geometry={nodes.Cylinder036_Material042_0.geometry}
                material={nodes.Cylinder036_Material042_0.material}
              />
            </group>
            <group position={[-763.86, 29.98, 74.81]} rotation={[-1.53, -0.03, 1.57]} scale={[13.99, 12.37, 17.5]}>
              <mesh
                geometry={nodes.Icosphere016_Material006_0.geometry}
                material={nodes.Icosphere016_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere016_Material026_0.geometry}
                material={nodes.Icosphere016_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere016_Material003_0.geometry}
                material={nodes.Icosphere016_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere016_Material016_0.geometry}
                material={nodes.Icosphere016_Material016_0.material}
              />
            </group>
            <group position={[-778.3, 29.98, 58.39]} rotation={[-1.57, -0.05, 0.59]} scale={[13.99, 12.37, 17.5]}>
              <mesh
                geometry={nodes.Icosphere017_Material006_0.geometry}
                material={nodes.Icosphere017_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere017_Material026_0.geometry}
                material={nodes.Icosphere017_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere017_Material003_0.geometry}
                material={nodes.Icosphere017_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere017_Material016_0.geometry}
                material={nodes.Icosphere017_Material016_0.material}
              />
            </group>
            <group position={[96.29, 8.08, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[95.72, 95.72, 9.49]}>
              <mesh
                geometry={nodes.Cylinder037_Material021_0.geometry}
                material={nodes.Cylinder037_Material021_0.material}
              />
            </group>
            <group position={[96.29, 74.87, 1.16]} rotation={[-Math.PI / 2, 0, -0.82]} scale={[51.18, 51.18, 5.08]}>
              <mesh
                geometry={nodes.Cylinder038_Material021_0.geometry}
                material={nodes.Cylinder038_Material021_0.material}
              />
            </group>
            <group position={[94.96, 104.44, 4.87]} rotation={[-Math.PI / 2, 0, -0.82]} scale={[24.24, 24.24, 2.4]}>
              <mesh
                geometry={nodes.Cylinder039_Material021_0.geometry}
                material={nodes.Cylinder039_Material021_0.material}
              />
            </group>
            <group position={[424.63, -1.63, -340.63]} rotation={[-1.8, -0.15, -1.72]} scale={[91.09, 91.09, 91.09]}>
              <mesh
                geometry={nodes.Tree1_small000_Material057_0.geometry}
                material={nodes.Tree1_small000_Material057_0.material}
              />
            </group>
            <group
              position={[-204.66, -31.72, 671.16]}
              rotation={[-1.76, -0.36, -0.73]}
              scale={[172.73, 172.73, 172.73]}
            >
              <mesh
                geometry={nodes.Tree1_small001_Material057_0.geometry}
                material={nodes.Tree1_small001_Material057_0.material}
              />
            </group>
            <group position={[558.29, 90.06, 415.73]} rotation={[-1.42, 0.08, -0.89]} scale={[226.01, 226.01, 226.01]}>
              <mesh geometry={nodes.Tree1000_Material005_0.geometry} material={nodes.Tree1000_Material005_0.material} />
              <mesh geometry={nodes.Tree1000_Material006_0.geometry} material={nodes.Tree1000_Material006_0.material} />
              <mesh geometry={nodes.Tree1000_Material003_0.geometry} material={nodes.Tree1000_Material003_0.material} />
              <mesh geometry={nodes.Tree1000_Material004_0.geometry} material={nodes.Tree1000_Material004_0.material} />
            </group>
            <group position={[-454.09, 75.26, -563.32]} rotation={[-1.66, 0.42, 0.72]} scale={[176.88, 176.88, 176.88]}>
              <mesh geometry={nodes.Tree1002_Material005_0.geometry} material={nodes.Tree1002_Material005_0.material} />
              <mesh geometry={nodes.Tree1002_Material006_0.geometry} material={nodes.Tree1002_Material006_0.material} />
              <mesh geometry={nodes.Tree1002_Material003_0.geometry} material={nodes.Tree1002_Material003_0.material} />
              <mesh geometry={nodes.Tree1002_Material004_0.geometry} material={nodes.Tree1002_Material004_0.material} />
            </group>
            <group position={[401.76, 139.43, -427.43]} rotation={[-1.14, -0.25, -3.1]} scale={[22.44, 22.44, 22.44]}>
              <mesh
                geometry={nodes.Tree1_small002_Material057_0.geometry}
                material={nodes.Tree1_small002_Material057_0.material}
              />
            </group>
            <group position={[292.33, 132.66, -378.72]} rotation={[-0.36, 0.64, -0.42]} scale={[22.44, 22.44, 22.44]}>
              <mesh
                geometry={nodes.Tree1_small003_Material057_0.geometry}
                material={nodes.Tree1_small003_Material057_0.material}
              />
            </group>
            <group position={[295.26, 134.22, -386.3]} rotation={[-1.43, 0.52, -1.35]} scale={[22.44, 22.44, 22.44]}>
              <mesh
                geometry={nodes.Tree1_small004_Material057_0.geometry}
                material={nodes.Tree1_small004_Material057_0.material}
              />
            </group>
            <group
              position={[-149.46, -31.72, 695.46]}
              rotation={[-1.38, -0.18, -2.76]}
              scale={[138.97, 138.97, 138.97]}
            >
              <mesh
                geometry={nodes.Tree1_small005_Material057_0.geometry}
                material={nodes.Tree1_small005_Material057_0.material}
              />
            </group>
            <group
              position={[-492.55, -13.54, 553.17]}
              rotation={[-1.76, -0.36, -0.73]}
              scale={[121.63, 121.63, 121.63]}
            >
              <mesh
                geometry={nodes.Tree1_small006_Material057_0.geometry}
                material={nodes.Tree1_small006_Material057_0.material}
              />
            </group>
            <group position={[-106.7, 18.1, -653.11]} rotation={[-1.58, -0.07, -1.26]} scale={[20.43, 23.59, 22.55]}>
              <mesh
                geometry={nodes.Icosphere018_Material006_0.geometry}
                material={nodes.Icosphere018_Material006_0.material}
              />
              <mesh
                geometry={nodes.Icosphere018_Material026_0.geometry}
                material={nodes.Icosphere018_Material026_0.material}
              />
              <mesh
                geometry={nodes.Icosphere018_Material003_0.geometry}
                material={nodes.Icosphere018_Material003_0.material}
              />
              <mesh
                geometry={nodes.Icosphere018_Material016_0.geometry}
                material={nodes.Icosphere018_Material016_0.material}
              />
            </group>
            <group
              position={[-433.31, -345.61, 860.84]}
              rotation={[-Math.PI / 2, 0, -0.46]}
              scale={[34.39, 84.99, 100]}
            >
              <mesh geometry={nodes.Plane011_Material036_0.geometry} material={materials["Material.036"]} />
            </group>
            <group position={[352.18, 130.91, -334.03]} rotation={[-0.88, 0.08, -2.16]} scale={[13.04, 13.04, 13.04]}>
              <mesh
                geometry={nodes.Tree1_small007_Material057_0.geometry}
                material={nodes.Tree1_small007_Material057_0.material}
              />
            </group>
            <group position={[-603.61, 595.44, 576.2]} rotation={[-Math.PI / 2, 0, 0.12]} scale={[33.58, 48.46, 36.06]}>
              <mesh
                geometry={nodes.Icosphere002_Material046_0.geometry}
                material={nodes.Icosphere002_Material046_0.material}
              />
            </group>
            <group position={[184.16, -4.69, 500.74]} rotation={[-2.66, 1.19, 1.12]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane015_Material005_0.geometry} material={nodes.Plane015_Material005_0.material} />
            </group>
            <group position={[132.99, -3.69, 199.12]} rotation={[-2.66, 1.19, 1.12]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane016_Material005_0.geometry} material={nodes.Plane016_Material005_0.material} />
            </group>
            <group position={[142.07, -3.69, 199.12]} rotation={[-0.43, 1.14, -1.18]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane017_Material005_0.geometry} material={nodes.Plane017_Material005_0.material} />
            </group>
            <group position={[113.63, -3.69, 204.41]} rotation={[-2.97, 0.03, 1.57]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane018_Material005_0.geometry} material={nodes.Plane018_Material005_0.material} />
            </group>
            <group position={[545.28, -1.22, -89.53]} rotation={[-2.66, 1.19, 1.12]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane019_Material005_0.geometry} material={nodes.Plane019_Material005_0.material} />
            </group>
            <group position={[554.36, -1.22, -89.53]} rotation={[-0.43, 1.14, -1.18]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane020_Material005_0.geometry} material={nodes.Plane020_Material005_0.material} />
            </group>
            <group position={[536.32, -1.22, -84.24]} rotation={[-2.97, 0.03, 1.57]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane021_Material005_0.geometry} material={nodes.Plane021_Material005_0.material} />
            </group>
            <group position={[402.61, 5.65, 221.21]} rotation={[-2.68, 1.17, 1.15]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane022_Material005_0.geometry} material={nodes.Plane022_Material005_0.material} />
            </group>
            <group position={[397.72, 5.65, 237.49]} rotation={[-2.91, -0.71, 1.72]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane023_Material005_0.geometry} material={nodes.Plane023_Material005_0.material} />
            </group>
            <group position={[-344.68, -5.14, -188.42]} rotation={[-0.18, 0.21, -1.53]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane024_Material005_0.geometry} material={nodes.Plane024_Material005_0.material} />
            </group>
            <group position={[-345.86, -5.14, -179.42]} rotation={[-0.2, -0.52, -1.67]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane025_Material005_0.geometry} material={nodes.Plane025_Material005_0.material} />
            </group>
            <group position={[-347.42, -5.14, -208.31]} rotation={[-0.83, 1.33, -0.76]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane026_Material005_0.geometry} material={nodes.Plane026_Material005_0.material} />
            </group>
            <group position={[57.66, -5.3, -435.58]} rotation={[-2.68, 1.17, 1.15]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane027_Material005_0.geometry} material={nodes.Plane027_Material005_0.material} />
            </group>
            <group position={[-163.82, -5.3, -194.26]} rotation={[-2.91, -0.71, 1.72]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane028_Material005_0.geometry} material={nodes.Plane028_Material005_0.material} />
            </group>
            <group position={[-469.55, -2.27, 646.69]} rotation={[-2.66, 1.19, 1.12]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane029_Material005_0.geometry} material={nodes.Plane029_Material005_0.material} />
            </group>
            <group position={[-300.89, -3.69, 439.11]} rotation={[-0.43, 1.14, -1.18]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane030_Material005_0.geometry} material={nodes.Plane030_Material005_0.material} />
            </group>
            <group position={[-329.34, -3.69, 444.4]} rotation={[-2.97, 0.03, 1.57]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane031_Material005_0.geometry} material={nodes.Plane031_Material005_0.material} />
            </group>
            <group position={[-310.95, -3.69, 450.58]} rotation={[-0.22, 0.66, -1.43]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane032_Material005_0.geometry} material={nodes.Plane032_Material005_0.material} />
            </group>
            <group position={[-308.01, -3.69, 459.17]} rotation={[-0.17, -0.06, -1.58]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane033_Material005_0.geometry} material={nodes.Plane033_Material005_0.material} />
            </group>
            <group position={[-322.22, -3.69, 433.97]} rotation={[-2.6, 1.23, 1.05]} scale={[19.3, 14, 19.3]}>
              <mesh geometry={nodes.Plane034_Material005_0.geometry} material={nodes.Plane034_Material005_0.material} />
            </group>
            <group position={[-543.37, 568.52, 396.35]} rotation={[-Math.PI / 2, 0, 0.12]} scale={[21.51, 31.05, 23.1]}>
              <mesh
                geometry={nodes.Icosphere011_Material046_0.geometry}
                material={nodes.Icosphere011_Material046_0.material}
              />
            </group>
            <group position={[-345.92, 130.78, 327.62]} rotation={[0, 0.56, -0.11]} scale={[100, 100, 100]} />
            <group
              position={[-662.45, -24.23, -405.41]}
              rotation={[-2.28, 0.07, 0.63]}
              scale={[121.63, 121.63, 121.63]}
            >
              <mesh
                geometry={nodes.Tree1_small008_Material057_0.geometry}
                material={nodes.Tree1_small008_Material057_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/floatingIsland/scene.gltf");
