/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: sosamatisosa (https://sketchfab.com/sosamatisosa)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cute-deer-fox-rig-9be1a69091fe4f6a8d70f09c6e6cd2b8
title: Cute Deer-Fox rig
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/fox/scene.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Walking.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={[0.16, 0.16, 0.16]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <primitive object={nodes._rootJoint} />
            <group position={[0, -0.87, 0]}>
              <group position={[0, -0.07, 0]}>
                <group position={[0, 2.79, -0.68]} rotation={[-0.09, 0, 0]}>
                  <group position={[0, 0.01, -0.43]} rotation={[-0.07, 0, 0]}>
                    <group position={[0, -0.02, -0.64]} rotation={[0.02, 0, 0]}>
                      <group position={[0, -0.02, -0.79]} rotation={[0.19, 0, 0]} />
                    </group>
                  </group>
                </group>
                <group position={[0.46, 2.39, -0.31]} rotation={[-0.12, 0, 0]}>
                  <group position={[0.1, -0.52, 0.01]} rotation={[0.43, 0.06, 0.19]}>
                    <group position={[0.03, -0.17, -0.32]} rotation={[-0.71, 0, 0]} />
                  </group>
                </group>
                <group position={[-0.46, 2.61, -0.22]} rotation={[-0.16, 0, 0]}>
                  <group position={[-0.1, -0.52, 0.01]} rotation={[0.26, -0.07, -0.28]}>
                    <group position={[-0.03, -0.17, -0.32]} rotation={[-0.88, 0, 0]} />
                  </group>
                </group>
                <group position={[0, -0.03, 0]}>
                  <group position={[0, 2.65, 1.52]} rotation={[0, 0, 0]}>
                    <group position={[0, 0.54, 0.36]}>
                      <group position={[-0.49, 0.46, 0.01]} rotation={[0, 0, 0.2]} />
                      <group position={[0.49, 0.46, 0.01]} rotation={[0, 0, -0.12]} />
                      <group position={[-0.51, 0.24, 0.63]} rotation={[0.15, 0.17, 1.7]}>
                        <mesh
                          geometry={nodes.Eye_R_Zorro_eyes_0.geometry}
                          material={nodes.Eye_R_Zorro_eyes_0.material}
                        />
                      </group>
                      <group position={[0.51, 0.24, 0.63]} rotation={[0.15, -0.17, -1.7]}>
                        <mesh
                          geometry={nodes.Eye_L_Zorro_eyes_0.geometry}
                          material={nodes.Eye_L_Zorro_eyes_0.material}
                        />
                      </group>
                      <group position={[0, -0.04, 0.87]} />
                    </group>
                  </group>
                  <group position={[-0.26, 2.48, 1.21]} rotation={[0.33, 0, 0]}>
                    <group position={[-0.26, -0.16, -0.03]} rotation={[0.29, 0, 0]}>
                      <group position={[-0.04, -0.58, 0.07]} rotation={[-1.58, 0, 0]} />
                    </group>
                  </group>
                  <group position={[0.26, 2.54, 1.32]} rotation={[-0.73, 0, 0]}>
                    <group position={[0.26, -0.16, -0.03]} rotation={[0.4, 0.13, 0.08]}>
                      <group position={[0.04, -0.58, 0.07]} rotation={[-1.87, 0, 0]} />
                    </group>
                  </group>
                </group>
              </group>
              <group position={[0.53, 1.47, 2.09]} rotation={[1.09, 0, 0]} />
              <group position={[-0.53, 1.15, 0.68]} rotation={[0.72, 0, 0]} />
              <group position={[-0.57, 1.2, -0.27]} rotation={[0.39, 0, 0]} />
              <group position={[0.57, 1.04, -0.44]} />
            </group>
            <skinnedMesh
              geometry={nodes.zorro_Zorro_piel_0.geometry}
              material={materials.Zorro_piel}
              skeleton={nodes.zorro_Zorro_piel_0.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/fox/scene.gltf");
