/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 3Dimentional (https://sketchfab.com/insectscorch)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-tree-game-asset-09ed6aeb11a74cc2bba18bc735d1fbed
title: Lowpoly Tree Game Asset
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.tree1_wood_tree_0.geometry} material={materials.wood_tree} />
            <mesh geometry={nodes.tree1_leaves_tree_0.geometry} material={materials.leaves_tree} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
