/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: DreamNoms (https://sketchfab.com/DreamNoms)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0cb6c35a8500427694747768186854c7
title: Gryphon Rigged and Animated
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/gryphon/scene.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Take 01"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group name="CatArmature" position={[0, 1.45, 6.54]} rotation={[1.56, 0, 0]} scale={[1.75, 1.75, 1.75]}>
          <primitive object={nodes.CatArmature_rootJoint} />
          <skinnedMesh
            geometry={nodes.Feathers000_0.geometry}
            material={nodes.Feathers000_0.material}
            skeleton={nodes.Feathers000_0.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Feathers000_1.geometry}
            material={nodes.Feathers000_1.material}
            skeleton={nodes.Feathers000_1.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Feathers003_0.geometry}
            material={nodes.Feathers003_0.material}
            skeleton={nodes.Feathers003_0.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Feathers003_1.geometry}
            material={nodes.Feathers003_1.material}
            skeleton={nodes.Feathers003_1.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_0.geometry}
            material={materials.White}
            skeleton={nodes.Body003_0.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_1.geometry}
            material={nodes.Body003_1.material}
            skeleton={nodes.Body003_1.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_2.geometry}
            material={nodes.Body003_2.material}
            skeleton={nodes.Body003_2.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_3.geometry}
            material={materials.Beak}
            skeleton={nodes.Body003_3.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_4.geometry}
            material={nodes.Body003_4.material}
            skeleton={nodes.Body003_4.skeleton}
          />
          <skinnedMesh
            geometry={nodes.Body003_5.geometry}
            material={materials.LayeringBack}
            skeleton={nodes.Body003_5.skeleton}
          />
        </group>
        <group position={[4.08, 1.01, 5.9]} rotation={[-0.27, 0.6, 1.93]} scale={[1, 1, 1]} />
        <group position={[4.08, -3.86, 5.9]} rotation={[-0.27, 0.6, 1.93]} scale={[1, 1, 1]} />
      </group>
    </group>
  );
}

useGLTF.preload("models/gryphon/scene.gltf");
