/* eslint-disable max-len */
/* eslint-disable react/jsx-props-no-spreading */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: arteknology (https://sketchfab.com/arteknology)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lowpoly-little-house-1eb62eecaeb044beb898bfa10fa3f2c1
title: LowPoly Little House
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.54, 0.06, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[1.94, 1.94, 1.94]}>
            <group position={[-0.9, 0.19, -1.15]} rotation={[0, 0, 0]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.pCube3_Pierres_0.geometry} material={nodes.pCube3_Pierres_0.material} />
            </group>
            <group position={[-0.9, 0.19, 1.15]} rotation={[0, 0, 0]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.pCube4_Pierres_0.geometry} material={nodes.pCube4_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.18, 1.15]} rotation={[0, 0, 0]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.pCube5_Pierres_0.geometry} material={nodes.pCube5_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.18, -1.15]} rotation={[0, 0, 0]} scale={[0.36, 0.36, 0.36]}>
              <mesh geometry={nodes.pCube6_Pierres_0.geometry} material={nodes.pCube6_Pierres_0.material} />
            </group>
            <group position={[-0.9, 0.59, -1.15]} rotation={[0, 0, 0]} scale={[0.28, 0.28, 0.28]}>
              <mesh geometry={nodes.pCube7_Pierres_0.geometry} material={nodes.pCube7_Pierres_0.material} />
            </group>
            <group position={[-0.9, 0.59, 1.15]} rotation={[0, 0, 0]} scale={[0.28, 0.28, 0.28]}>
              <mesh geometry={nodes.pCube8_Pierres_0.geometry} material={nodes.pCube8_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.58, -1.15]} rotation={[0, 0, 0]} scale={[0.28, 0.28, 0.28]}>
              <mesh geometry={nodes.pCube9_Pierres_0.geometry} material={nodes.pCube9_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.58, 1.15]} rotation={[0, 0, 0]} scale={[0.28, 0.28, 0.28]}>
              <mesh geometry={nodes.pCube10_Pierres_0.geometry} material={nodes.pCube10_Pierres_0.material} />
            </group>
            <group position={[-0.9, 0.92, -1.15]} rotation={[0, 0, 0]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.pCube11_Pierres_0.geometry} material={nodes.pCube11_Pierres_0.material} />
            </group>
            <group position={[-0.9, 0.92, 1.15]} rotation={[0, 0, 0]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.pCube12_Pierres_0.geometry} material={nodes.pCube12_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.91, -1.15]} rotation={[0, 0, 0]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.pCube13_Pierres_0.geometry} material={nodes.pCube13_Pierres_0.material} />
            </group>
            <group position={[0.88, 0.91, 1.15]} rotation={[0, 0, 0]} scale={[0.31, 0.31, 0.31]}>
              <mesh geometry={nodes.pCube14_Pierres_0.geometry} material={nodes.pCube14_Pierres_0.material} />
            </group>
            <group position={[-0.9, 1.28, -1.15]} rotation={[0, 0, 0]} scale={[0.44, 0.32, 0.44]}>
              <mesh geometry={nodes.pCube15_Pierres_0.geometry} material={nodes.pCube15_Pierres_0.material} />
            </group>
            <group position={[-0.9, 1.28, 1.15]} rotation={[0, 0, 0]} scale={[0.44, 0.32, 0.44]}>
              <mesh geometry={nodes.pCube16_Pierres_0.geometry} material={nodes.pCube16_Pierres_0.material} />
            </group>
            <group position={[0.88, 1.27, -1.15]} rotation={[0, 0, 0]} scale={[0.44, 0.32, 0.44]}>
              <mesh geometry={nodes.pCube17_Pierres_0.geometry} material={nodes.pCube17_Pierres_0.material} />
            </group>
            <group position={[0.88, 1.27, 1.15]} rotation={[0, 0, 0]} scale={[0.44, 0.32, 0.44]}>
              <mesh geometry={nodes.pCube18_Pierres_0.geometry} material={nodes.pCube18_Pierres_0.material} />
            </group>
            <group position={[-0.9, 1.67, -1.15]} rotation={[0, 0, 0]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.pCube19_Pierres_0.geometry} material={nodes.pCube19_Pierres_0.material} />
            </group>
            <group position={[-0.9, 1.67, 1.15]} rotation={[0, 0, 0]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.pCube20_Pierres_0.geometry} material={nodes.pCube20_Pierres_0.material} />
            </group>
            <group position={[0.88, 1.66, -1.15]} rotation={[0, 0, 0]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.pCube21_Pierres_0.geometry} material={nodes.pCube21_Pierres_0.material} />
            </group>
            <group position={[0.88, 1.66, 1.15]} rotation={[0, 0, 0]} scale={[0.37, 0.37, 0.37]}>
              <mesh geometry={nodes.pCube22_Pierres_0.geometry} material={nodes.pCube22_Pierres_0.material} />
            </group>
            <group position={[0, -0.01, 0]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.porte_Poutres_0.geometry} material={nodes.porte_Poutres_0.material} />
            </group>
            <group position={[0.01, 0.49, 1.15]} rotation={[0, 0, 0]} scale={[0.6, 0.98, 0.36]}>
              <mesh geometry={nodes.encadrement_Pierres_0.geometry} material={nodes.encadrement_Pierres_0.material} />
            </group>
            <group position={[0.85, 1.05, 0.38]} rotation={[0, 0, 0]} scale={[0.45, 0.45, 0.45]}>
              <mesh geometry={nodes.pCube31_Poutres_0.geometry} material={nodes.pCube31_Poutres_0.material} />
            </group>
            <group position={[0.85, 1.05, -0.4]} rotation={[0, 0, 0]} scale={[0.45, 0.45, 0.45]}>
              <mesh geometry={nodes.pCube32_Poutres_0.geometry} material={nodes.pCube32_Poutres_0.material} />
            </group>
            <group position={[-0.83, 1.05, -0.4]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.45, 0.45, 0.45]}>
              <mesh geometry={nodes.pCube33_Poutres_0.geometry} material={nodes.pCube33_Poutres_0.material} />
            </group>
            <group position={[-0.83, 1.05, 0.41]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.45, 0.45, 0.45]}>
              <mesh geometry={nodes.pCube34_Poutres_0.geometry} material={nodes.pCube34_Poutres_0.material} />
            </group>
            <group position={[-0.03, 1.02, -1.11]} rotation={[0, Math.PI / 2, 0]} scale={[0.45, 0.68, 0.45]}>
              <mesh geometry={nodes.pCube56_Poutres_0.geometry} material={nodes.pCube56_Poutres_0.material} />
            </group>
            <group position={[0.85, 1.06, 0.38]} rotation={[0, 0, 0]} scale={[0.34, 0.38, 0.37]}>
              <mesh geometry={nodes.pCube58_vitres1_0.geometry} material={nodes.pCube58_vitres1_0.material} />
            </group>
            <group position={[0.85, 1.06, -0.4]} rotation={[0, 0, 0]} scale={[0.34, 0.38, 0.37]}>
              <mesh geometry={nodes.pCube59_vitres1_0.geometry} material={nodes.pCube59_vitres1_0.material} />
            </group>
            <group position={[-0.85, 1.06, -0.4]} rotation={[0, 0, 0]} scale={[0.34, 0.38, 0.37]}>
              <mesh geometry={nodes.pCube60_vitres1_0.geometry} material={nodes.pCube60_vitres1_0.material} />
            </group>
            <group position={[-0.85, 1.06, 0.41]} rotation={[0, 0, 0]} scale={[0.34, 0.38, 0.37]}>
              <mesh geometry={nodes.pCube61_vitres1_0.geometry} material={nodes.pCube61_vitres1_0.material} />
            </group>
            <group position={[-0.03, 1, -1.09]} rotation={[0, 0, 0]} scale={[0.35, 0.65, 0.37]}>
              <mesh geometry={nodes.pCube62_vitres1_0.geometry} material={nodes.pCube62_vitres1_0.material} />
            </group>
            <group position={[0.01, 2.26, 1.39]} rotation={[0, 0, 0]} scale={[0.89, 0.78, 0.37]}>
              <mesh geometry={nodes.pCube108_vitres1_0.geometry} material={nodes.pCube108_vitres1_0.material} />
            </group>
            <group position={[0.01, 2.26, -1.37]} rotation={[0, 0, 0]} scale={[0.89, 0.78, 0.37]}>
              <mesh geometry={nodes.pCube143_vitres1_0.geometry} material={nodes.pCube143_vitres1_0.material} />
            </group>
            <group position={[-0.02, 0, 0]}>
              <mesh geometry={nodes.pCube71_Poutres_0.geometry} material={nodes.pCube71_Poutres_0.material} />
            </group>
            <group position={[-0.03, 0.65, 1.42]} rotation={[-1.55, 0, 0]}>
              <mesh geometry={nodes.pCube72_Poutres_0.geometry} material={nodes.pCube72_Poutres_0.material} />
            </group>
            <group position={[-0.02, 0, -0.79]}>
              <mesh geometry={nodes.pCube73_Poutres_0.geometry} material={nodes.pCube73_Poutres_0.material} />
            </group>
            <group position={[-0.03, 0.65, 0.63]} rotation={[-1.55, 0, 0]}>
              <mesh geometry={nodes.pCube74_Poutres_0.geometry} material={nodes.pCube74_Poutres_0.material} />
            </group>
            <group position={[-2.07, 0.65, 0.64]} rotation={[-1.55, 0, 0]}>
              <mesh geometry={nodes.pCube75_Poutres_0.geometry} material={nodes.pCube75_Poutres_0.material} />
            </group>
            <group position={[-2.06, 0, -0.78]}>
              <mesh geometry={nodes.pCube76_Poutres_0.geometry} material={nodes.pCube76_Poutres_0.material} />
            </group>
            <group position={[-2.07, 0.65, 1.45]} rotation={[-1.55, 0, 0]}>
              <mesh geometry={nodes.pCube77_Poutres_0.geometry} material={nodes.pCube77_Poutres_0.material} />
            </group>
            <group position={[-2.06, 0, 0.03]}>
              <mesh geometry={nodes.pCube78_Poutres_0.geometry} material={nodes.pCube78_Poutres_0.material} />
            </group>
            <group position={[0, 1.87, 1.55]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube35_Poutres_0.geometry} material={nodes.pCube35_Poutres_0.material} />
            </group>
            <group position={[0, 1.87, -1.54]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube36_Poutres_0.geometry} material={nodes.pCube36_Poutres_0.material} />
            </group>
            <group position={[1.38, 1.87, -0.24]} rotation={[0, Math.PI / 2, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube37_Poutres_0.geometry} material={nodes.pCube37_Poutres_0.material} />
            </group>
            <group position={[-1.37, 1.87, -0.24]} rotation={[0, Math.PI / 2, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube38_Poutres_0.geometry} material={nodes.pCube38_Poutres_0.material} />
            </group>
            <group position={[1.32, 2.15, 1.53]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube39_Poutres_0.geometry} material={nodes.pCube39_Poutres_0.material} />
            </group>
            <group position={[-1.32, 2.15, 1.53]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube40_Poutres_0.geometry} material={nodes.pCube40_Poutres_0.material} />
            </group>
            <group position={[-1.32, 2.15, -1.53]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube41_Poutres_0.geometry} material={nodes.pCube41_Poutres_0.material} />
            </group>
            <group position={[1.32, 2.15, -1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube42_Poutres_0.geometry} material={nodes.pCube42_Poutres_0.material} />
            </group>
            <group position={[-0.51, 0.24, 1.29]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube44_Poutres_0.geometry} material={nodes.pCube44_Poutres_0.material} />
            </group>
            <group position={[-0.51, 1.49, 1.36]} rotation={[0.87, 0, Math.PI / 2]} scale={[0.1, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube45_Poutres_0.geometry} material={nodes.pCube45_Poutres_0.material} />
            </group>
            <mesh geometry={nodes.pCube57_Poutres_0.geometry} material={nodes.pCube57_Poutres_0.material} />
            <group position={[1.02, 0, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.pCube48_Poutres_0.geometry} material={nodes.pCube48_Poutres_0.material} />
            </group>
            <group position={[-0.02, 0, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.pCube49_Poutres_0.geometry} material={nodes.pCube49_Poutres_0.material} />
            </group>
            <group position={[-0.63, 0, 1.3]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube50_Poutres_0.geometry} material={nodes.pCube50_Poutres_0.material} />
            </group>
            <group position={[-0.63, 0, 0.51]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube51_Poutres_0.geometry} material={nodes.pCube51_Poutres_0.material} />
            </group>
            <group position={[-0.63, 0, -0.28]} rotation={[0, Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube52_Poutres_0.geometry} material={nodes.pCube52_Poutres_0.material} />
            </group>
            <group position={[0.63, 0, -1.3]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube53_Poutres_0.geometry} material={nodes.pCube53_Poutres_0.material} />
            </group>
            <group position={[0.63, 0, -0.51]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube54_Poutres_0.geometry} material={nodes.pCube54_Poutres_0.material} />
            </group>
            <group position={[0.63, 0, 0.28]} rotation={[0, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.pCube55_Poutres_0.geometry} material={nodes.pCube55_Poutres_0.material} />
            </group>
            <group position={[-0.03, 0.97, -1.24]} rotation={[0, 0, Math.PI / 2]} scale={[0.47, 0.05, 0.15]}>
              <mesh geometry={nodes.pCube79_Poutres_0.geometry} material={nodes.pCube79_Poutres_0.material} />
            </group>
            <group position={[0.01, 1.02, -1.24]} rotation={[0, 0, Math.PI]} scale={[0.33, 0.05, 0.15]}>
              <mesh geometry={nodes.pCube80_Poutres_0.geometry} material={nodes.pCube80_Poutres_0.material} />
            </group>
            <group position={[-0.51, 2.29, 1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube81_Poutres_0.geometry} material={nodes.pCube81_Poutres_0.material} />
            </group>
            <group position={[0.51, 2.29, 1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube82_Poutres_0.geometry} material={nodes.pCube82_Poutres_0.material} />
            </group>
            <group position={[0, 2.7, 1.55]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube83_Poutres_0.geometry} material={nodes.pCube83_Poutres_0.material} />
            </group>
            <group position={[-1.16, 2.49, 1.52]} rotation={[0, 0, 0.7]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube84_Poutres_0.geometry} material={nodes.pCube84_Poutres_0.material} />
            </group>
            <group position={[1.16, 2.48, 1.53]} rotation={[3.04, -0.13, -2.44]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube85_Poutres_0.geometry} material={nodes.pCube85_Poutres_0.material} />
            </group>
            <group position={[0, 3.11, 1.54]} rotation={[0, 0, 0]} scale={[1.46, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube86_Poutres_0.geometry} material={nodes.pCube86_Poutres_0.material} />
            </group>
            <group position={[0.01, 3.35, 1.53]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube87_Poutres_0.geometry} material={nodes.pCube87_Poutres_0.material} />
            </group>
            <group position={[-0.22, 2.88, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube88_Poutres_0.geometry} material={nodes.pCube88_Poutres_0.material} />
            </group>
            <group position={[0.23, 2.88, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube89_Poutres_0.geometry} material={nodes.pCube89_Poutres_0.material} />
            </group>
            <group position={[0.51, 2.29, -1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube90_Poutres_0.geometry} material={nodes.pCube90_Poutres_0.material} />
            </group>
            <group position={[-0.51, 2.29, -1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube91_Poutres_0.geometry} material={nodes.pCube91_Poutres_0.material} />
            </group>
            <group position={[-1.16, 2.49, -1.54]} rotation={[0, 0, 0.7]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube92_Poutres_0.geometry} material={nodes.pCube92_Poutres_0.material} />
            </group>
            <group position={[0, 2.7, -1.53]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube93_Poutres_0.geometry} material={nodes.pCube93_Poutres_0.material} />
            </group>
            <group position={[0.23, 2.88, -1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube94_Poutres_0.geometry} material={nodes.pCube94_Poutres_0.material} />
            </group>
            <group position={[-0.22, 2.88, -1.5]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube95_Poutres_0.geometry} material={nodes.pCube95_Poutres_0.material} />
            </group>
            <group position={[0, 3.11, -1.53]} rotation={[0, 0, 0]} scale={[1.46, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube96_Poutres_0.geometry} material={nodes.pCube96_Poutres_0.material} />
            </group>
            <group position={[0.01, 3.36, -1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.42, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube97_Poutres_0.geometry} material={nodes.pCube97_Poutres_0.material} />
            </group>
            <group position={[1.16, 2.48, -1.54]} rotation={[3.04, -0.13, -2.44]} scale={[0.47, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube98_Poutres_0.geometry} material={nodes.pCube98_Poutres_0.material} />
            </group>
            <group position={[0.51, 1.87, 1.37]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube99_Poutres_0.geometry} material={nodes.pCube99_Poutres_0.material} />
            </group>
            <group position={[-0.51, 1.87, 1.37]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube100_Poutres_0.geometry} material={nodes.pCube100_Poutres_0.material} />
            </group>
            <group position={[0.51, 1.87, -1.36]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube101_Poutres_0.geometry} material={nodes.pCube101_Poutres_0.material} />
            </group>
            <group position={[-0.53, 1.87, -1.36]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube102_Poutres_0.geometry} material={nodes.pCube102_Poutres_0.material} />
            </group>
            <group
              position={[1.29, 2.34, -0.24]}
              rotation={[Math.PI / 2, 1.32, -Math.PI / 2]}
              scale={[2.45, 0.13, 0.15]}
            >
              <mesh geometry={nodes.pCube103_Poutres_0.geometry} material={nodes.pCube103_Poutres_0.material} />
            </group>
            <group
              position={[-1.3, 2.34, -0.24]}
              rotation={[-Math.PI / 2, 1.35, Math.PI / 2]}
              scale={[2.45, 0.13, 0.15]}
            >
              <mesh geometry={nodes.pCube104_Poutres_0.geometry} material={nodes.pCube104_Poutres_0.material} />
            </group>
            <group position={[1.2, 1.87, 0.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube105_Poutres_0.geometry} material={nodes.pCube105_Poutres_0.material} />
            </group>
            <group position={[1.2, 1.87, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube106_Poutres_0.geometry} material={nodes.pCube106_Poutres_0.material} />
            </group>
            <group position={[1.2, 1.87, -0.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube107_Poutres_0.geometry} material={nodes.pCube107_Poutres_0.material} />
            </group>
            <group position={[-0.29, 2.29, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube109_Poutres_0.geometry} material={nodes.pCube109_Poutres_0.material} />
            </group>
            <group position={[-0.09, 2.29, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube110_Poutres_0.geometry} material={nodes.pCube110_Poutres_0.material} />
            </group>
            <group position={[0.11, 2.29, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube111_Poutres_0.geometry} material={nodes.pCube111_Poutres_0.material} />
            </group>
            <group position={[0.3, 2.29, 1.51]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube112_Poutres_0.geometry} material={nodes.pCube112_Poutres_0.material} />
            </group>
            <group position={[0, 2.52, 1.52]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube113_Poutres_0.geometry} material={nodes.pCube113_Poutres_0.material} />
            </group>
            <group position={[0, 2.36, 1.52]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube114_Poutres_0.geometry} material={nodes.pCube114_Poutres_0.material} />
            </group>
            <group position={[0, 2.2, 1.52]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube115_Poutres_0.geometry} material={nodes.pCube115_Poutres_0.material} />
            </group>
            <group position={[0, 2.03, 1.52]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube116_Poutres_0.geometry} material={nodes.pCube116_Poutres_0.material} />
            </group>
            <group position={[-1.2, 1.87, 0.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube117_Poutres_0.geometry} material={nodes.pCube117_Poutres_0.material} />
            </group>
            <group position={[-1.2, 1.87, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube118_Poutres_0.geometry} material={nodes.pCube118_Poutres_0.material} />
            </group>
            <group position={[-1.2, 1.87, -0.79]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.71, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube119_Poutres_0.geometry} material={nodes.pCube119_Poutres_0.material} />
            </group>
            <group position={[0.02, 3.74, -0.27]} rotation={[-Math.PI / 2, 0.75, Math.PI / 2]} scale={[3.35, 0.2, 0.2]}>
              <mesh geometry={nodes.pCube122_Poutres_0.geometry} material={nodes.pCube122_Poutres_0.material} />
            </group>
            <group position={[-0.01, 2.36, -1.5]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube144_Poutres_0.geometry} material={nodes.pCube144_Poutres_0.material} />
            </group>
            <group position={[-0.29, 2.29, -1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube145_Poutres_0.geometry} material={nodes.pCube145_Poutres_0.material} />
            </group>
            <group position={[-0.01, 2.52, -1.5]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube146_Poutres_0.geometry} material={nodes.pCube146_Poutres_0.material} />
            </group>
            <group position={[-0.01, 2.2, -1.5]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube147_Poutres_0.geometry} material={nodes.pCube147_Poutres_0.material} />
            </group>
            <group position={[-0.1, 2.29, -1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube148_Poutres_0.geometry} material={nodes.pCube148_Poutres_0.material} />
            </group>
            <group position={[-0.01, 2.03, -1.5]} rotation={[0, 0, 0]} scale={[1.45, 0.06, 0.14]}>
              <mesh geometry={nodes.pCube149_Poutres_0.geometry} material={nodes.pCube149_Poutres_0.material} />
            </group>
            <group position={[0.1, 2.29, -1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube150_Poutres_0.geometry} material={nodes.pCube150_Poutres_0.material} />
            </group>
            <group position={[0.3, 2.29, -1.52]} rotation={[0, 0, Math.PI / 2]} scale={[0.71, 0.06, 0.15]}>
              <mesh geometry={nodes.pCube151_Poutres_0.geometry} material={nodes.pCube151_Poutres_0.material} />
            </group>
            <group position={[0, 1.33, 1.28]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube1024_Poutres_0.geometry} material={nodes.pCube1024_Poutres_0.material} />
            </group>
            <group position={[0, 1.59, 1.24]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube1025_Poutres_0.geometry} material={nodes.pCube1025_Poutres_0.material} />
            </group>
            <group position={[-0.99, 1.61, -0.24]} rotation={[0, Math.PI / 2, 0]} scale={[1.93, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube1026_Poutres_0.geometry} material={nodes.pCube1026_Poutres_0.material} />
            </group>
            <group position={[0.99, 1.61, -0.24]} rotation={[0, Math.PI / 2, 0]} scale={[1.93, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube1027_Poutres_0.geometry} material={nodes.pCube1027_Poutres_0.material} />
            </group>
            <group position={[0, 1.59, -1.25]} rotation={[0, 0, 0]} scale={[2.74, 0.13, 0.15]}>
              <mesh geometry={nodes.pCube1028_Poutres_0.geometry} material={nodes.pCube1028_Poutres_0.material} />
            </group>
            <group position={[0, 0.93, 0]} rotation={[0, 0, 0]} scale={[2.02, 1.84, 2.53]}>
              <mesh geometry={nodes.Base_Base1_0.geometry} material={nodes.Base_Base1_0.material} />
            </group>
            <group position={[0, 2.51, 0]} rotation={[0, 0, 0]} scale={[2.74, 1.4, 3.11]}>
              <mesh geometry={nodes.bastoit_Base1_0.geometry} material={nodes.bastoit_Base1_0.material} />
            </group>
            <group position={[0.71, 3.34, 0.03]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1.6, 1.6, 3.65]}>
              <mesh geometry={nodes.pCube121_Poutres_0.geometry} material={nodes.pCube121_Poutres_0.material} />
            </group>
            <group position={[-0.69, 3.34, 0.03]} rotation={[0, 0, 0]} scale={[1.6, 1.6, 3.65]}>
              <mesh geometry={nodes.pCube120_Poutres_0.geometry} material={nodes.pCube120_Poutres_0.material} />
            </group>
            <group position={[0, 0.37, 0.05]} rotation={[0, 0, 0]} scale={[0.91, 0.91, 0.91]}>
              <group position={[0.07, 0, 0.1]} rotation={[-Math.PI, 0, -Math.PI]}>
                <group rotation={[0, 0, 0]}>
                  <mesh geometry={nodes.TOITGAUCHE_toit1_0.geometry} material={nodes.TOITGAUCHE_toit1_0.material} />
                </group>
              </group>
              <group rotation={[0, 0, 0]}>
                <group rotation={[0, 0, 0]}>
                  <mesh geometry={nodes.TOITGAUCHE_toit1_0_1.geometry} material={nodes.TOITGAUCHE_toit1_0_1.material} />
                </group>
              </group>
            </group>
            <group position={[0.07, 0, 0.1]} rotation={[-Math.PI, 0, -Math.PI]}>
              <mesh geometry={nodes.TOITGAUCHE_toit1_0_2.geometry} material={nodes.TOITGAUCHE_toit1_0_2.material} />
            </group>
            <mesh geometry={nodes.TOITGAUCHE_toit1_0_3.geometry} material={nodes.TOITGAUCHE_toit1_0_3.material} />
          </group>
          <group scale={[24.04, 0.19, 24.04]}>
            <mesh geometry={nodes.plateforme_herbe_0.geometry} material={materials.herbe} />
          </group>
          <group position={[-16.51, -0.47, -10.81]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0.geometry} material={nodes.pCube982_arbre25_0.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0.geometry} material={nodes.pCube981_arbre25_0.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0.geometry} material={nodes.pCube980_arbre25_0.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0.geometry} material={nodes.pCube979_arbre25_0.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0.geometry} material={nodes.tron_tron1_0.material} />
            </group>
          </group>
          <group position={[-0.85, -0.47, -1.07]} rotation={[0, -0.39, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_1.geometry} material={nodes.pCube982_arbre25_0_1.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_1.geometry} material={nodes.pCube981_arbre25_0_1.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_1.geometry} material={nodes.pCube980_arbre25_0_1.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_1.geometry} material={nodes.pCube979_arbre25_0_1.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_1.geometry} material={nodes.tron_tron1_0_1.material} />
            </group>
          </group>
          <group position={[-6.68, -0.47, 0.49]} rotation={[0, -0.71, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_2.geometry} material={nodes.pCube982_arbre25_0_2.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_2.geometry} material={nodes.pCube981_arbre25_0_2.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_2.geometry} material={nodes.pCube980_arbre25_0_2.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_2.geometry} material={nodes.pCube979_arbre25_0_2.material} />
            </group>
            <group position={[0.05, 1.98, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_2.geometry} material={nodes.tron_tron1_0_2.material} />
            </group>
          </group>
          <group position={[-13.06, -0.47, -8.29]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_3.geometry} material={nodes.pCube982_arbre25_0_3.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_3.geometry} material={nodes.pCube981_arbre25_0_3.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_3.geometry} material={nodes.pCube980_arbre25_0_3.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_3.geometry} material={nodes.pCube979_arbre25_0_3.material} />
            </group>
            <group position={[0.05, 1.99, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_3.geometry} material={nodes.tron_tron1_0_3.material} />
            </group>
          </group>
          <group position={[-10.95, -0.47, -11.32]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_4.geometry} material={nodes.pCube982_arbre25_0_4.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_4.geometry} material={nodes.pCube981_arbre25_0_4.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_4.geometry} material={nodes.pCube980_arbre25_0_4.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_4.geometry} material={nodes.pCube979_arbre25_0_4.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_4.geometry} material={nodes.tron_tron1_0_4.material} />
            </group>
          </group>
          <group position={[-2.68, -0.47, 13.66]} rotation={[0, -0.39, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_5.geometry} material={nodes.pCube982_arbre25_0_5.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_5.geometry} material={nodes.pCube981_arbre25_0_5.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_5.geometry} material={nodes.pCube980_arbre25_0_5.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_5.geometry} material={nodes.pCube979_arbre25_0_5.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_5.geometry} material={nodes.tron_tron1_0_5.material} />
            </group>
          </group>
          <group position={[-6.65, -0.47, 16.68]} rotation={[0, -0.71, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_6.geometry} material={nodes.pCube982_arbre25_0_6.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_6.geometry} material={nodes.pCube981_arbre25_0_6.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_6.geometry} material={nodes.pCube980_arbre25_0_6.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_6.geometry} material={nodes.pCube979_arbre25_0_6.material} />
            </group>
            <group position={[0.05, 1.93, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_6.geometry} material={nodes.tron_tron1_0_6.material} />
            </group>
          </group>
          <group position={[-14.89, -0.47, 8.76]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_7.geometry} material={nodes.pCube982_arbre25_0_7.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_7.geometry} material={nodes.pCube981_arbre25_0_7.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_7.geometry} material={nodes.pCube980_arbre25_0_7.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_7.geometry} material={nodes.pCube979_arbre25_0_7.material} />
            </group>
            <group position={[0.05, 1.95, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_7.geometry} material={nodes.tron_tron1_0_7.material} />
            </group>
          </group>
          <group position={[-12.05, -0.47, 5.79]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_8.geometry} material={nodes.pCube982_arbre25_0_8.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_8.geometry} material={nodes.pCube981_arbre25_0_8.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_8.geometry} material={nodes.pCube980_arbre25_0_8.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_8.geometry} material={nodes.pCube979_arbre25_0_8.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_8.geometry} material={nodes.tron_tron1_0_8.material} />
            </group>
          </group>
          <group position={[-2.57, -0.13, 16.33]} rotation={[0, -0.71, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_9.geometry} material={nodes.pCube982_arbre25_0_9.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_9.geometry} material={nodes.pCube981_arbre25_0_9.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_9.geometry} material={nodes.pCube980_arbre25_0_9.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_9.geometry} material={nodes.pCube979_arbre25_0_9.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_9.geometry} material={nodes.tron_tron1_0_9.material} />
            </group>
          </group>
          <group position={[1.29, -0.47, 1.68]} rotation={[0, -0.44, 0]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_10.geometry} material={nodes.pCube982_arbre25_0_10.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_10.geometry} material={nodes.pCube981_arbre25_0_10.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_10.geometry} material={nodes.pCube980_arbre25_0_10.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_10.geometry} material={nodes.pCube979_arbre25_0_10.material} />
            </group>
            <group position={[0.05, 1.97, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_10.geometry} material={nodes.tron_tron1_0_10.material} />
            </group>
          </group>
          <group position={[-0.52, -0.47, -10.53]} rotation={[-Math.PI, -1.49, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_11.geometry} material={nodes.pCube982_arbre25_0_11.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_11.geometry} material={nodes.pCube981_arbre25_0_11.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_11.geometry} material={nodes.pCube980_arbre25_0_11.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_11.geometry} material={nodes.pCube979_arbre25_0_11.material} />
            </group>
            <group position={[0.05, 1.95, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_11.geometry} material={nodes.tron_tron1_0_11.material} />
            </group>
          </group>
          <group position={[1.8, -0.47, 2.49]} rotation={[0, -0.88, 0]}>
            <group position={[0, 4.94, -8.33]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_12.geometry} material={nodes.pCube982_arbre25_0_12.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_12.geometry} material={nodes.pCube981_arbre25_0_12.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_12.geometry} material={nodes.pCube980_arbre25_0_12.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_12.geometry} material={nodes.pCube979_arbre25_0_12.material} />
            </group>
            <group position={[0.05, 1.94, -8.32]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_12.geometry} material={nodes.tron_tron1_0_12.material} />
            </group>
          </group>
          <group position={[9.42, -0.47, 9.94]} rotation={[0, -0.1, 0]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_13.geometry} material={nodes.pCube982_arbre25_0_13.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_13.geometry} material={nodes.pCube981_arbre25_0_13.material} />
            </group>
            <group position={[0, 4.52, -8.33]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_13.geometry} material={nodes.pCube980_arbre25_0_13.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_13.geometry} material={nodes.pCube979_arbre25_0_13.material} />
            </group>
            <group position={[0.05, 1.92, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_13.geometry} material={nodes.tron_tron1_0_13.material} />
            </group>
          </group>
          <group position={[12.91, -0.47, 8.77]} rotation={[0, 1.26, 0]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_14.geometry} material={nodes.pCube982_arbre25_0_14.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_14.geometry} material={nodes.pCube981_arbre25_0_14.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_14.geometry} material={nodes.pCube980_arbre25_0_14.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_14.geometry} material={nodes.pCube979_arbre25_0_14.material} />
            </group>
            <group position={[0.05, 1.97, -8.32]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_14.geometry} material={nodes.tron_tron1_0_14.material} />
            </group>
          </group>
          <group position={[3.7, -0.47, 1.48]} rotation={[-Math.PI, -0.85, -Math.PI]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_15.geometry} material={nodes.pCube982_arbre25_0_15.material} />
            </group>
            <group position={[0, 4.04, -8.33]} rotation={[0, 0, 0]}>
              <mesh geometry={nodes.pCube981_arbre25_0_15.geometry} material={nodes.pCube981_arbre25_0_15.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_15.geometry} material={nodes.pCube980_arbre25_0_15.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_15.geometry} material={nodes.pCube979_arbre25_0_15.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_15.geometry} material={nodes.tron_tron1_0_15.material} />
            </group>
          </group>
          <group position={[-0.98, -0.47, 11.47]} rotation={[0, -1.43, 0]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_16.geometry} material={nodes.pCube982_arbre25_0_16.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_16.geometry} material={nodes.pCube981_arbre25_0_16.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_16.geometry} material={nodes.pCube980_arbre25_0_16.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_16.geometry} material={nodes.pCube979_arbre25_0_16.material} />
            </group>
            <group position={[0.05, 1.96, -8.32]} rotation={[0, 0, 0]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_16.geometry} material={nodes.tron_tron1_0_16.material} />
            </group>
          </group>
          <group position={[2.43, -0.47, -4.08]} rotation={[0, -1.3, 0]}>
            <group position={[0, 4.94, -8.33]} rotation={[0, 0, 0]} scale={[0.49, 0.49, 0.49]}>
              <mesh geometry={nodes.pCube982_arbre25_0_17.geometry} material={nodes.pCube982_arbre25_0_17.material} />
            </group>
            <group position={[0, 4.04, -8.33]}>
              <mesh geometry={nodes.pCube981_arbre25_0_17.geometry} material={nodes.pCube981_arbre25_0_17.material} />
            </group>
            <group position={[0, 4.52, -8.33]} rotation={[0, 0, 0]} scale={[0.77, 0.77, 0.77]}>
              <mesh geometry={nodes.pCube980_arbre25_0_17.geometry} material={nodes.pCube980_arbre25_0_17.material} />
            </group>
            <group position={[0, 3.21, -8.32]} rotation={[-Math.PI, -0.04, -Math.PI]} scale={[1.67, 1.67, 1.67]}>
              <mesh geometry={nodes.pCube979_arbre25_0_17.geometry} material={nodes.pCube979_arbre25_0_17.material} />
            </group>
            <group position={[0.05, 1.93, -8.32]} scale={[0.38, 2.83, 0.35]}>
              <mesh geometry={nodes.tron_tron1_0_17.geometry} material={nodes.tron_tron1_0_17.material} />
            </group>
          </group>
          <group position={[-6.48, 0.22, -3.71]} scale={[0.38, 0.38, 0.38]}>
            <mesh geometry={nodes.pCube990_lambert1_0.geometry} material={nodes.pCube990_lambert1_0.material} />
          </group>
          <group position={[-4.58, 0.22, -5.39]} rotation={[0, -0.84, 0]} scale={[0.5, 0.5, 0.5]}>
            <mesh geometry={nodes.pCube991_lambert1_0.geometry} material={nodes.pCube991_lambert1_0.material} />
          </group>
          <group position={[-5.39, 0.22, 2.74]} rotation={[0, -0.22, 0]} scale={[0.45, 0.45, 0.45]}>
            <mesh geometry={nodes.pCube992_lambert1_0.geometry} material={nodes.pCube992_lambert1_0.material} />
          </group>
          <group position={[-1.32, 0.32, 8.51]} rotation={[0, 0.41, 0]} scale={[0.71, 0.71, 0.71]}>
            <mesh geometry={nodes.pCube993_lambert1_0.geometry} material={nodes.pCube993_lambert1_0.material} />
          </group>
          <group position={[1.2, 0.34, -8.65]} rotation={[0, 0.35, 0]} scale={[0.64, 0.64, 0.64]}>
            <mesh geometry={nodes.pCube994_lambert1_0.geometry} material={nodes.pCube994_lambert1_0.material} />
          </group>
          <group position={[-7.85, 0.22, 3.26]} rotation={[0, -0.62, 0]} scale={[0.33, 0.33, 0.33]}>
            <mesh geometry={nodes.pCube995_lambert1_0.geometry} material={nodes.pCube995_lambert1_0.material} />
          </group>
          <group position={[-7.8, 0.22, -9.16]} rotation={[0, 1.25, 0]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.pCube996_lambert1_0.geometry} material={nodes.pCube996_lambert1_0.material} />
          </group>
          <group position={[-9.81, 0.27, -8.04]} rotation={[0, 0.07, 0]} scale={[0.57, 0.57, 0.72]}>
            <mesh geometry={nodes.pCube997_lambert1_0.geometry} material={nodes.pCube997_lambert1_0.material} />
          </group>
          <group position={[-8.28, 0.22, -5.78]} rotation={[0, 1.25, 0]} scale={[0.31, 0.31, 0.31]}>
            <mesh geometry={nodes.pCube998_lambert1_0.geometry} material={nodes.pCube998_lambert1_0.material} />
          </group>
          <group position={[-9.03, 0.22, 7.82]} rotation={[0, 1.25, 0]} scale={[0.41, 0.41, 0.41]}>
            <mesh geometry={nodes.pCube999_lambert1_0.geometry} material={nodes.pCube999_lambert1_0.material} />
          </group>
          <group position={[-10.56, 0.27, 4.64]} rotation={[2.79, 1.13, -2.82]} scale={[0.57, 0.57, 0.72]}>
            <mesh geometry={nodes.pCube1000_lambert1_0.geometry} material={nodes.pCube1000_lambert1_0.material} />
          </group>
          <group position={[-7.04, 0.22, 5.28]} rotation={[0, 1.25, 0]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.pCube1001_lambert1_0.geometry} material={nodes.pCube1001_lambert1_0.material} />
          </group>
          <group position={[-11.03, 0.27, -10.49]} rotation={[0, 1.23, 0]} scale={[0.42, 0.42, 0.52]}>
            <mesh geometry={nodes.pCube1002_lambert1_0.geometry} material={nodes.pCube1002_lambert1_0.material} />
          </group>
          <group position={[-10.56, 0.2, 10.16]} rotation={[0.02, 0.54, -0.16]} scale={[0.46, 0.46, 0.57]}>
            <mesh geometry={nodes.pCube1003_lambert1_0.geometry} material={nodes.pCube1003_lambert1_0.material} />
          </group>
          <group position={[10.19, 0.22, -3.71]} rotation={[0, 1.38, 0]} scale={[0.38, 0.38, 0.38]}>
            <mesh geometry={nodes.pCube1004_lambert1_0.geometry} material={nodes.pCube1004_lambert1_0.material} />
          </group>
          <group position={[10.7, 0.22, -9.83]} rotation={[0, 0.54, 0]} scale={[0.5, 0.5, 0.5]}>
            <mesh geometry={nodes.pCube1005_lambert1_0.geometry} material={nodes.pCube1005_lambert1_0.material} />
          </group>
          <group position={[11.28, 0.22, 2.74]} rotation={[0, 1.16, 0]} scale={[0.45, 0.45, 0.45]}>
            <mesh geometry={nodes.pCube1006_lambert1_0.geometry} material={nodes.pCube1006_lambert1_0.material} />
          </group>
          <group position={[10.97, 0.32, 10.74]} rotation={[-Math.PI, 1.36, -Math.PI]} scale={[0.71, 0.71, 0.71]}>
            <mesh geometry={nodes.pCube1007_lambert1_0.geometry} material={nodes.pCube1007_lambert1_0.material} />
          </group>
          <group position={[7.03, 0.34, -1.56]} rotation={[-Math.PI, 1.42, -Math.PI]} scale={[0.64, 0.64, 0.64]}>
            <mesh geometry={nodes.pCube1008_lambert1_0.geometry} material={nodes.pCube1008_lambert1_0.material} />
          </group>
          <group position={[8.82, 0.22, 3.26]} rotation={[0, 0.75, 0]} scale={[0.33, 0.33, 0.33]}>
            <mesh geometry={nodes.pCube1009_lambert1_0.geometry} material={nodes.pCube1009_lambert1_0.material} />
          </group>
          <group position={[8.87, 0.22, -9.16]} rotation={[-Math.PI, 0.52, -Math.PI]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.pCube1010_lambert1_0.geometry} material={nodes.pCube1010_lambert1_0.material} />
          </group>
          <group position={[6.85, 0.27, -8.04]} rotation={[0, 1.45, 0]} scale={[0.57, 0.57, 0.72]}>
            <mesh geometry={nodes.pCube1011_lambert1_0.geometry} material={nodes.pCube1011_lambert1_0.material} />
          </group>
          <group position={[8.39, 0.22, -5.78]} rotation={[-Math.PI, 0.52, -Math.PI]} scale={[0.31, 0.31, 0.31]}>
            <mesh geometry={nodes.pCube1012_lambert1_0.geometry} material={nodes.pCube1012_lambert1_0.material} />
          </group>
          <group position={[7.64, 0.22, 7.82]} rotation={[-Math.PI, 0.52, -Math.PI]} scale={[0.41, 0.41, 0.41]}>
            <mesh geometry={nodes.pCube1013_lambert1_0.geometry} material={nodes.pCube1013_lambert1_0.material} />
          </group>
          <group position={[6.11, 0.27, 4.64]} rotation={[3.11, -0.22, -3]} scale={[0.57, 0.57, 0.72]}>
            <mesh geometry={nodes.pCube1014_lambert1_0.geometry} material={nodes.pCube1014_lambert1_0.material} />
          </group>
          <group position={[9.63, 0.22, 5.28]} rotation={[-Math.PI, 0.52, -Math.PI]} scale={[0.24, 0.24, 0.24]}>
            <mesh geometry={nodes.pCube1015_lambert1_0.geometry} material={nodes.pCube1015_lambert1_0.material} />
          </group>
          <group position={[5.64, 0.27, -10.49]} rotation={[-Math.PI, 0.53, -Math.PI]} scale={[0.42, 0.42, 0.52]}>
            <mesh geometry={nodes.pCube1016_lambert1_0.geometry} material={nodes.pCube1016_lambert1_0.material} />
          </group>
          <group position={[6.11, 0.2, 10.16]} rotation={[2.72, 1.2, -2.76]} scale={[0.46, 0.46, 0.57]}>
            <mesh geometry={nodes.pCube1017_lambert1_0.geometry} material={nodes.pCube1017_lambert1_0.material} />
          </group>
          <group position={[-9.8, 0.51, -11.91]} rotation={[Math.PI, -0.01, Math.PI]} scale={[-1.47, 0.74, 1.35]}>
            <group position={[1.41, -0.42, -8.53]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube989_Pierres_0.geometry} material={nodes.pCube989_Pierres_0.material} />
            </group>
            <group position={[2.02, -0.42, -8.54]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube988_Pierres_0.geometry} material={nodes.pCube988_Pierres_0.material} />
            </group>
            <group position={[2.63, -0.42, -8.54]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube987_Pierres_0.geometry} material={nodes.pCube987_Pierres_0.material} />
            </group>
            <group position={[3.86, -0.42, -8.55]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube985_Pierres_0.geometry} material={nodes.pCube985_Pierres_0.material} />
            </group>
            <group position={[4.47, -0.42, -8.56]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube984_Pierres_0.geometry} material={nodes.pCube984_Pierres_0.material} />
            </group>
            <group position={[5.08, -0.42, -8.56]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube983_Pierres_0.geometry} material={nodes.pCube983_Pierres_0.material} />
            </group>
            <group position={[3.25, -0.42, -8.55]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube986_Pierres_0.geometry} material={nodes.pCube986_Pierres_0.material} />
            </group>
            <group position={[0.75, -0.42, -8.53]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube1018_Pierres_0.geometry} material={nodes.pCube1018_Pierres_0.material} />
            </group>
            <group position={[0.14, -0.42, -8.52]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube1020_Pierres_0.geometry} material={nodes.pCube1020_Pierres_0.material} />
            </group>
            <group position={[-0.47, -0.42, -8.52]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube1022_Pierres_0.geometry} material={nodes.pCube1022_Pierres_0.material} />
            </group>
            <group position={[-1.09, -0.42, -8.51]} rotation={[-1.58, 0, 0]} scale={[0.45, 0.12, 0.05]}>
              <mesh geometry={nodes.pCube1023_Pierres_0.geometry} material={nodes.pCube1023_Pierres_0.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
