/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: SGD114101 (https://sketchfab.com/SGD114101)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/kitchen-scene-670c5b1fa9ed499cbb2b5f5bd48294e0
title: Kitchen Scene
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/kitchen/scene.gltf");
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group name="papertowelsGroup" position={[-55.92, 40.12, -41.07]}>
            <group position={[0, 7.14, 0]} scale={[3.5, 3.5, 3.5]}>
              <mesh
                geometry={nodes.paperTowel_holder_redMat_0.geometry}
                material={nodes.paperTowel_holder_redMat_0.material}
              />
            </group>
            <group position={[-0.02, 7.68, -0.06]} rotation={[0.01, 0, 0]} scale={[3.5, 3.5, 3.5]}>
              <mesh
                geometry={nodes.paperTowels_white_Mat_0.geometry}
                material={nodes.paperTowels_white_Mat_0.material}
              />
            </group>
          </group>
          <group name="tableGroup">
            <group position={[-3.86, 24.03, 40.59]} rotation={[3.12, 0.01, 3.11]}>
              <mesh geometry={nodes.cushion_02_redMat_0.geometry} material={nodes.cushion_02_redMat_0.material} />
            </group>
            <mesh geometry={nodes.chair_01_tan_Mat_0.geometry} material={nodes.chair_01_tan_Mat_0.material} />
            <group position={[-1.74, 0.47, -8.05]} rotation={[0, -0.05, 0]}>
              <mesh geometry={nodes.chair_02_tan_Mat_0.geometry} material={nodes.chair_02_tan_Mat_0.material} />
            </group>
            <mesh geometry={nodes.table_tan_Mat_0.geometry} material={nodes.table_tan_Mat_0.material} />
            <group position={[35.82, -0.97, 90.07]} rotation={[-3.13, 0.03, -3.1]}>
              <mesh geometry={nodes.cushion_01_redMat_0.geometry} material={nodes.cushion_01_redMat_0.material} />
            </group>
          </group>
          <group position={[54.38, 34.72, -0.63]} rotation={[0, -0.8, 0]} scale={[11.51, 9.25, 11.51]}>
            <mesh
              geometry={nodes.trashCan_body_shinyMetalMat_0.geometry}
              material={nodes.trashCan_body_shinyMetalMat_0.material}
            />
          </group>
          <group position={[-27.86, 10.98, 17.47]} rotation={[-0.03, 1.38, 0.02]} scale={[0.86, 0.72, 0.7]}>
            <mesh geometry={nodes.bottle_shinyMetalMat_0.geometry} material={nodes.bottle_shinyMetalMat_0.material} />
          </group>
          <mesh
            geometry={nodes.trashCan_lid_shinyMetalMat_0.geometry}
            material={nodes.trashCan_lid_shinyMetalMat_0.material}
          />
          <group position={[45.74, -2.01, 104.94]}>
            <group position={[-23.11, 39.62, -68.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.38, 1.58, 1.38]}>
              <mesh geometry={nodes.Plate_shinyMetalMat_0.geometry} material={nodes.Plate_shinyMetalMat_0.material} />
            </group>
            <group position={[-37.09, 11.37, -13.75]} rotation={[-0.27, -0.69, 0]} scale={[0.52, 0.98, 0.71]}>
              <mesh geometry={nodes.banana_1_yellowMat_0.geometry} material={nodes.banana_1_yellowMat_0.material} />
            </group>
            <group position={[9.02, 0, -17.1]}>
              <mesh geometry={nodes.banana_2_yellowMat_0.geometry} material={nodes.banana_2_yellowMat_0.material} />
            </group>
            <group position={[-23.26, 39.82, -63.36]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.29, 1.24, 1.17]}>
              <mesh geometry={nodes.Pear_greenMat_0.geometry} material={nodes.Pear_greenMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_1_orangeMat_0.geometry} material={nodes.orange_1_orangeMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_2_orangeMat_0.geometry} material={nodes.orange_2_orangeMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_3_orangeMat_0.geometry} material={nodes.orange_3_orangeMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_4_orangeMat_0.geometry} material={nodes.orange_4_orangeMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_5_orangeMat_0.geometry} material={nodes.orange_5_orangeMat_0.material} />
            </group>
            <group position={[-20.54, 39.69, -67.64]} rotation={[-Math.PI, -0.69, -Math.PI]} scale={[1.58, 1.58, 1.58]}>
              <mesh geometry={nodes.orange_6_orangeMat_0.geometry} material={nodes.orange_6_orangeMat_0.material} />
            </group>
            <group position={[9.02, 0, -17.1]}>
              <mesh geometry={nodes.apple_redMat_0.geometry} material={nodes.apple_redMat_0.material} />
              <mesh geometry={nodes.apple_tan_Mat_0.geometry} material={nodes.apple_tan_Mat_0.material} />
              <mesh geometry={nodes.apple_greenMat_0.geometry} material={nodes.apple_greenMat_0.material} />
            </group>
          </group>
          <mesh geometry={nodes.CounterTop_white_Mat_0.geometry} material={nodes.CounterTop_white_Mat_0.material} />
          <mesh geometry={nodes.CounterTop_brownMat_0.geometry} material={nodes.CounterTop_brownMat_0.material} />
          <mesh geometry={nodes.window_brownMat_0.geometry} material={nodes.window_brownMat_0.material} />
          <group position={[0.33, 50.03, -3.93]} rotation={[-Math.PI / 2, 0, 0]} scale={[14, 10, 10]}>
            <mesh geometry={nodes.Floor_white_Mat_0.geometry} material={nodes.Floor_white_Mat_0.material} />
          </group>
          <group position={[0, 50, -2.98]} rotation={[-Math.PI / 2, 0, 0]} scale={[14, 10, 10]}>
            <mesh geometry={nodes.walls_yellowMat_0.geometry} material={nodes.walls_yellowMat_0.material} />
          </group>
          <group position={[48.42, 75.84, -41.52]} scale={[0.86, 0.76, 0.49]}>
            <mesh geometry={nodes.TopCabinet_brownMat_0.geometry} material={nodes.TopCabinet_brownMat_0.material} />
          </group>
          <group position={[42.9, 51.27, -53.16]} scale={[0.27, 0.1, 0.02]}>
            <mesh geometry={nodes.wallSocket_white_Mat_0.geometry} material={nodes.wallSocket_white_Mat_0.material} />
          </group>
          <group position={[37.29, 73.89, -27.97]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet1_tan_Mat_0.geometry} material={nodes.cabinet1_tan_Mat_0.material} />
          </group>
          <group position={[57.07, 73.89, -27.97]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet2_tan_Mat_0.geometry} material={nodes.cabinet2_tan_Mat_0.material} />
          </group>
          <group position={[-55.66, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet3_tan_Mat_0.geometry} material={nodes.cabinet3_tan_Mat_0.material} />
          </group>
          <group position={[-35.88, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet4_tan_Mat_0.geometry} material={nodes.cabinet4_tan_Mat_0.material} />
          </group>
          <group position={[-13.51, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet5_tan_Mat_0.geometry} material={nodes.cabinet5_tan_Mat_0.material} />
          </group>
          <group position={[6.28, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet6_tan_Mat_0.geometry} material={nodes.cabinet6_tan_Mat_0.material} />
          </group>
          <group position={[26.71, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet7_tan_Mat_0.geometry} material={nodes.cabinet7_tan_Mat_0.material} />
          </group>
          <group position={[37.29, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet8_tan_Mat_0.geometry} material={nodes.cabinet8_tan_Mat_0.material} />
          </group>
          <group position={[57.07, 16.36, -22.81]} scale={[0.38, 0.51, 0.05]}>
            <mesh geometry={nodes.cabinet9_tan_Mat_0.geometry} material={nodes.cabinet9_tan_Mat_0.material} />
          </group>
          <group position={[-55.66, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer1_tan_Mat_0.geometry} material={nodes.drawer1_tan_Mat_0.material} />
          </group>
          <group position={[-35.88, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer2_tan_Mat_0.geometry} material={nodes.drawer2_tan_Mat_0.material} />
          </group>
          <group position={[26.71, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer3_tan_Mat_0.geometry} material={nodes.drawer3_tan_Mat_0.material} />
          </group>
          <group position={[37.29, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer4_tan_Mat_0.geometry} material={nodes.drawer4_tan_Mat_0.material} />
          </group>
          <group position={[6.28, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer5_tan_Mat_0.geometry} material={nodes.drawer5_tan_Mat_0.material} />
          </group>
          <group position={[-13.51, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer6_tan_Mat_0.geometry} material={nodes.drawer6_tan_Mat_0.material} />
          </group>
          <group position={[57.07, 33.6, -22.81]} scale={[0.38, 0.15, 0.05]}>
            <mesh geometry={nodes.drawer7_tan_Mat_0.geometry} material={nodes.drawer7_tan_Mat_0.material} />
          </group>
          <group position={[44.62, 53.63, -25.76]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob1_shinyMetalMat_0.geometry} material={nodes.Knob1_shinyMetalMat_0.material} />
          </group>
          <group position={[49.94, 53.63, -25.76]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob2_shinyMetalMat_0.geometry} material={nodes.Knob2_shinyMetalMat_0.material} />
          </group>
          <group position={[57.14, 33.69, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob3_shinyMetalMat_0.geometry} material={nodes.Knob3_shinyMetalMat_0.material} />
          </group>
          <group position={[49.94, 25.16, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob4_shinyMetalMat_0.geometry} material={nodes.Knob4_shinyMetalMat_0.material} />
          </group>
          <group position={[44.62, 25.16, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob5_shinyMetalMat_0.geometry} material={nodes.Knob5_shinyMetalMat_0.material} />
          </group>
          <group position={[37.75, 33.69, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob6_shinyMetalMat_0.geometry} material={nodes.Knob6_shinyMetalMat_0.material} />
          </group>
          <group position={[21.81, 33.69, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob7_shinyMetalMat_0.geometry} material={nodes.Knob7_shinyMetalMat_0.material} />
          </group>
          <group position={[19.63, 25.16, -20.59]} rotation={[Math.PI / 2, 0, 0]} scale={[1.35, 1.35, 1.35]}>
            <mesh geometry={nodes.Knob8_shinyMetalMat_0.geometry} material={nodes.Knob8_shinyMetalMat_0.material} />
          </group>
          <mesh geometry={nodes.Faucet_shinyMetalMat_0.geometry} material={nodes.Faucet_shinyMetalMat_0.material} />
          <group position={[-11.53, 42.02, -48.39]} scale={[1.51, 0.46, 1.51]}>
            <mesh
              geometry={nodes.LeftHandle_shinyMetalMat_0.geometry}
              material={nodes.LeftHandle_shinyMetalMat_0.material}
            />
          </group>
          <group position={[-4.42, 40.18, -37.31]} scale={[1.51, 1.47, 0.73]}>
            <mesh geometry={nodes.Sink_shinyMetalMat_0.geometry} material={nodes.Sink_shinyMetalMat_0.material} />
          </group>
          <group position={[3.28, 42.02, -48.39]} scale={[1.51, 0.46, 1.51]}>
            <mesh
              geometry={nodes.RightHandle_shinyMetalMat_0.geometry}
              material={nodes.RightHandle_shinyMetalMat_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/kitchen/scene.gltf");
