/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: denaum4uk (https://sketchfab.com/denaum4uk)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/damage-kitchen-boy-5b47168abb944754af3f1bc98fea0510
title: damage kitchen boy
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[538.13, 22.3, 324.59]} rotation={[Math.PI, 0.57, -2.96]} />
          <group position={[10.26, 138.86, -128.56]}>
            <group position={[0, 1.39, -0.02]} rotation={[Math.PI, 0, Math.PI]} scale={[-1.08, -0.06, -1]}>
              <mesh
                geometry={nodes['������������_������_1_����������������3_0'].geometry}
                material={nodes['������������_������_1_����������������3_0'].material}
              />
            </group>
            <group position={[0, -1.39, 0.02]}>
              <mesh
                geometry={nodes['������������_������_����������������10_0'].geometry}
                material={nodes['������������_������_����������������10_0'].material}
              />
            </group>
          </group>
          <group position={[-213.07, 147.68, -143.32]} rotation={[0, 0.48, 0]} scale={[0.25, 0.27, 0.26]}>
            <group position={[-2.26, -8.5, -65.36]} rotation={[0.02, -0.03, -1.61]} scale={[0.93, 1.08, 1]}>
              <mesh
                geometry={nodes['������������_����������_����������������11_0'].geometry}
                material={nodes['������������_����������_����������������11_0'].material}
              />
            </group>
            <group position={[3.4, 1.85, 72.26]} rotation={[1.03, 0, 0]}>
              <mesh
                geometry={nodes['������������_��������������_����������������11_0'].geometry}
                material={nodes['������������_��������������_����������������11_0'].material}
              />
            </group>
            <group position={[-1.14, 6.64, -6.9]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_����������������11_0_1'].geometry}
                material={nodes['������������_����������_����������������11_0_1'].material}
              />
            </group>
          </group>
          <group position={[-167.23, 88.28, -144.63]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_2_����������������_0'].geometry}
                material={nodes['������������_��������������_2_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_����������������_0'].geometry}
                material={nodes['������������_����������_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_����������������_0'].geometry}
                material={nodes['������������_����������_1_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-167.23, 85.3, -144.63]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_3_����������������_0'].geometry}
                material={nodes['������������_��������������_3_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_2_����������������_0'].geometry}
                material={nodes['������������_����������_2_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_2_����������������_0'].geometry}
                material={nodes['������������_����������_1_2_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-167.23, 81.82, -144.63]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_4_����������������_0'].geometry}
                material={nodes['������������_��������������_4_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_3_����������������_0'].geometry}
                material={nodes['������������_����������_3_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_3_����������������_0'].geometry}
                material={nodes['������������_����������_1_3_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[108.66, 44.52, 128.79]}>
            <group position={[12.91, -3.15, 7.03]} rotation={[-0.06, -0.09, -0.05]}>
              <mesh
                geometry={nodes['������������_����������_2_����������������9_0'].geometry}
                material={nodes['������������_����������_2_����������������9_0'].material}
              />
            </group>
            <group position={[19.44, -10.82, 1.9]} rotation={[-0.24, -0.08, -0.06]}>
              <mesh
                geometry={nodes['������������_����������_1_����������������8_0'].geometry}
                material={nodes['������������_����������_1_����������������8_0'].material}
              />
            </group>
            <group position={[9.93, -4.88, 12.35]} rotation={[-0.59, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_2_2_����������������7_0'].geometry}
                material={nodes['������������_����������_2_2_����������������7_0'].material}
              />
            </group>
          </group>
          <group position={[-144.96, 91.27, -139.77]} rotation={[0, 0, -0.9]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_5_����������������_0'].geometry}
                material={nodes['������������_��������������_5_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_4_����������������_0'].geometry}
                material={nodes['������������_����������_4_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_4_����������������_0'].geometry}
                material={nodes['������������_����������_1_4_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-151, 90.49, -139.77]} rotation={[0, 0, -0.9]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_6_����������������_0'].geometry}
                material={nodes['������������_��������������_6_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_5_����������������_0'].geometry}
                material={nodes['������������_����������_5_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_5_����������������_0'].geometry}
                material={nodes['������������_����������_1_5_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-167.23, 78.84, -144.63]}>
            <group position={[-2.02, 55.42, -0.91]} rotation={[0, -0.42, 0]}>
              <mesh
                geometry={nodes['������������_��������������_7_����������������_0'].geometry}
                material={nodes['������������_��������������_7_����������������_0'].material}
              />
            </group>
            <group position={[-1.85, 57.1, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_6_����������������_0'].geometry}
                material={nodes['������������_����������_6_����������������_0'].material}
              />
            </group>
            <group position={[-1.95, 53.25, 0]} rotation={[0, 0, 3.13]}>
              <mesh
                geometry={nodes['������������_����������_1_6_����������������_0'].geometry}
                material={nodes['������������_����������_1_6_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-162.66, 143.65, -1.8]}>
            <group position={[-2.07, 0, 4.27]}>
              <mesh
                geometry={nodes['������������_����������_2_3_����������������10_0'].geometry}
                material={nodes['������������_����������_2_3_����������������10_0'].material}
              />
            </group>
            <group position={[-2.07, 0, -6.07]}>
              <mesh
                geometry={nodes['������������_����������_1_2_����������������10_0'].geometry}
                material={nodes['������������_����������_1_2_����������������10_0'].material}
              />
            </group>
            <group position={[4.14, 0, 1.8]}>
              <mesh
                geometry={nodes['������������_����������_3_����������������10_0'].geometry}
                material={nodes['������������_����������_3_����������������10_0'].material}
              />
            </group>
          </group>
          <group position={[-186.48, 135, -10.01]} rotation={[-0.01, -1.34, -0.05]}>
            <group position={[-1.14, 0, 13.75]} rotation={[0, 0, 0]} scale={[0.84, 0.71, 1.19]}>
              <mesh
                geometry={nodes['������������_����������_2_����������������9_0_1'].geometry}
                material={nodes['������������_����������_2_����������������9_0_1'].material}
              />
            </group>
            <group position={[1.14, 0, -13.75]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_2_����������������9_0'].geometry}
                material={nodes['������������_������_2_����������������9_0'].material}
              />
            </group>
          </group>
          <group position={[-220.46, -7.92, -140.37]} rotation={[0, 0, -1.55]}>
            <group rotation={[0, 0, 0]}>
              <group position={[-138.32, 170.96, 0]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_��������������_8_����������������8_0'].geometry}
                  material={nodes['������������_��������������_8_����������������8_0'].material}
                />
              </group>
              <group position={[-138.32, 173.31, 0]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_��������������_1_����������������8_0'].geometry}
                  material={nodes['������������_��������������_1_����������������8_0'].material}
                />
              </group>
            </group>
          </group>
          <group position={[-34.71, -244.69, -347.4]} rotation={[0, 0, 0.04]}>
            <group position={[0, 386.32, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_4_����������������_0_1'].geometry}
                material={nodes['������������_����������_4_����������������_0_1'].material}
              />
            </group>
            <group position={[0, 388.42, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_1_3_����������������_0_1'].geometry}
                material={nodes['������������_����������_1_3_����������������_0_1'].material}
              />
            </group>
          </group>
          <group position={[-34.42, -251.45, -347.4]} rotation={[0, 0, 0.04]}>
            <group position={[0, 386.32, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_5_����������������_0_1'].geometry}
                material={nodes['������������_����������_5_����������������_0_1'].material}
              />
            </group>
            <group position={[0, 388.42, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_1_4_����������������_0_1'].geometry}
                material={nodes['������������_����������_1_4_����������������_0_1'].material}
              />
            </group>
          </group>
          <group position={[3.63, -254.51, -347.4]} rotation={[0, 0, 0.14]}>
            <group position={[0, 386.32, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_6_����������������_0_1'].geometry}
                material={nodes['������������_����������_6_����������������_0_1'].material}
              />
            </group>
            <group position={[0, 388.42, 201.88]}>
              <mesh
                geometry={nodes['������������_����������_1_5_����������������_0_1'].geometry}
                material={nodes['������������_����������_1_5_����������������_0_1'].material}
              />
            </group>
          </group>
          <group position={[-157.71, -236.16, -255.55]}>
            <group position={[-24.06, 0, 0]}>
              <group position={[0, 386.32, 201.88]}>
                <mesh
                  geometry={nodes['������������_����������_7_����������������_0_1'].geometry}
                  material={nodes['������������_����������_7_����������������_0_1'].material}
                />
              </group>
              <group position={[0, 388.42, 201.88]}>
                <mesh
                  geometry={nodes['������������_����������_1_6_����������������_0_1'].geometry}
                  material={nodes['������������_����������_1_6_����������������_0_1'].material}
                />
              </group>
            </group>
          </group>
          <group position={[29.35, -42.75, -106.6]}>
            <group position={[-138.32, 170.96, 0]}>
              <mesh
                geometry={nodes['������������_��������������_9_����������������8_0'].geometry}
                material={nodes['������������_��������������_9_����������������8_0'].material}
              />
            </group>
            <group position={[-138.32, 173.31, 0]}>
              <mesh
                geometry={nodes['������������_��������������_1_2_����������������8_0'].geometry}
                material={nodes['������������_��������������_1_2_����������������8_0'].material}
              />
            </group>
          </group>
          <group position={[-213.9, 146.18, -71.67]} scale={[0.84, 0.92, 0.81]}>
            <group position={[0, 4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_1_3_����������������3_0'].geometry}
                material={nodes['������������_��������������_1_3_����������������3_0'].material}
              />
            </group>
            <group position={[0, -4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_10_����������������_0'].geometry}
                material={nodes['������������_��������������_10_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-195.6, 141.9, -91.86]} scale={[0.72, 0.63, 0.79]}>
            <group position={[0, 4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_1_4_����������������4_0'].geometry}
                material={nodes['������������_��������������_1_4_����������������4_0'].material}
              />
            </group>
            <group position={[0, -4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_11_����������������_0'].geometry}
                material={nodes['������������_��������������_11_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-219.95, 148.81, -102.48]}>
            <group position={[0, 4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_1_5_����������������7_0'].geometry}
                material={nodes['������������_��������������_1_5_����������������7_0'].material}
              />
            </group>
            <group position={[0, -4.95, 0]}>
              <mesh
                geometry={nodes['������������_��������������_12_����������������_0'].geometry}
                material={nodes['������������_��������������_12_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[-154.67, 51.63, 50.79]} rotation={[0, -1.3, 0.24]}>
            <group position={[0.01, -43.11, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_1_2_Boy01_Hands_MAT_0'].geometry}
                material={nodes['������������_������_1_2_Boy01_Hands_MAT_0'].material}
              />
            </group>
            <group position={[-0.06, -27.05, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_3_����������������7_0'].geometry}
                material={nodes['������������_������_3_����������������7_0'].material}
              />
            </group>
            <group position={[0.05, 70.16, 0]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_��������������_1_6_����������������7_0'].geometry}
                material={nodes['������������_��������������_1_6_����������������7_0'].material}
              />
            </group>
          </group>
          <group position={[-107.98, 287.57, 0]}>
            <group position={[1.72, -33.96, 0]} rotation={[-1.58, 0, 0]}>
              <group rotation={[Math.PI / 2, 0, 0]} />
            </group>
            <group position={[1.97, -4.37, -0.53]} rotation={[1.34, 0.25, -3.02]}>
              <mesh
                geometry={nodes['������������_����������_8_����������������10_0'].geometry}
                material={nodes['������������_����������_8_����������������10_0'].material}
              />
            </group>
            <group position={[2.85, 5.26, -0.22]} rotation={[0, 0, 0.02]}>
              <mesh
                geometry={nodes['������������_����������_3_2_Boy01_UpperBody_MAT_1_0'].geometry}
                material={nodes['������������_����������_3_2_Boy01_UpperBody_MAT_1_0'].material}
              />
            </group>
            <group position={[2.74, 9.61, -0.22]} rotation={[0, 0, 0.02]}>
              <mesh
                geometry={nodes['������������_����������_2_2_����������������_0'].geometry}
                material={nodes['������������_����������_2_2_����������������_0'].material}
              />
            </group>
            <group position={[3.02, 24.54, 0]}>
              <mesh
                geometry={nodes['������������_��������������_13_Boy01_UpperBody_MAT_1_0'].geometry}
                material={nodes['������������_��������������_13_Boy01_UpperBody_MAT_1_0'].material}
              />
            </group>
            <group position={[3.5, 36.78, -0.22]} rotation={[0, 0, -3.12]}>
              <mesh
                geometry={nodes['������������_����������_1_7_����������������_0'].geometry}
                material={nodes['������������_����������_1_7_����������������_0'].material}
              />
            </group>
            <group position={[3.36, 42.74, -0.22]} rotation={[0, 0, -3.12]}>
              <mesh
                geometry={nodes['������������_����������_7_����������������_0'].geometry}
                material={nodes['������������_����������_7_����������������_0'].material}
              />
            </group>
            <group position={[0, 23.56, 0]}>
              <group position={[3.16, -31.55, -0.22]} rotation={[0, 0, 0.02]}>
                <mesh
                  geometry={nodes['������������_����������_4_2_Boy01_UpperBody_MAT_1_0'].geometry}
                  material={nodes['������������_����������_4_2_Boy01_UpperBody_MAT_1_0'].material}
                />
              </group>
              <group position={[3.2, -33.02, -0.22]} rotation={[0, 0, 0.02]}>
                <mesh
                  geometry={nodes['������������_����������_5_2_����������������_0'].geometry}
                  material={nodes['������������_����������_5_2_����������������_0'].material}
                />
              </group>
            </group>
          </group>
          <group position={[-138.18, 9.03, 131.6]}>
            <group position={[-0.17, -42.63, -0.51]}>
              <group position={[-18.96, 51.53, -12.93]} rotation={[0, -0.69, -0.1]}>
                <mesh
                  geometry={nodes['������������_������_1_0_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_0_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[12.93, 51.53, -18.96]} rotation={[-3.14, -0.88, 3.04]}>
                <mesh
                  geometry={nodes['������������_������_1_1_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_1_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[18.96, 51.53, 12.93]} rotation={[-3.14, 0.69, 3.04]}>
                <mesh
                  geometry={nodes['������������_������_1_2_2_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_2_2_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[-12.93, 51.53, 18.96]} rotation={[0, 0.88, -0.1]}>
                <mesh
                  geometry={nodes['������������_������_1_3_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_3_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
            </group>
            <group position={[0.57, 70.48, 0.27]} rotation={[0, -0.69, 0]}>
              <mesh
                geometry={nodes['������������_������_4_Boy01_Hair_MAT_1_0'].geometry}
                material={nodes['������������_������_4_Boy01_Hair_MAT_1_0'].material}
              />
            </group>
            <group position={[-0.4, -27.85, 0.24]} rotation={[0, 0.53, 0]}>
              <group position={[-14.38, 57.21, 33.42]} rotation={[0, -1.01, 0]} scale={[0.04, 0.41, 0.03]}>
                <mesh
                  geometry={nodes['������������_������_0_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_0_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[-32.88, 57.21, -15.56]} rotation={[Math.PI, -0.52, Math.PI]} scale={[0.04, 0.41, 0.03]}>
                <mesh
                  geometry={nodes['������������_������_1_3_2_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_3_2_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[15.06, 57.21, -33.12]} rotation={[Math.PI, 1.03, -Math.PI]} scale={[0.04, 0.41, 0.03]}>
                <mesh
                  geometry={nodes['������������_������_2_2_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_2_2_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[32.71, 57.21, 15.92]} rotation={[0, 0.51, 0]} scale={[0.04, 0.41, 0.03]}>
                <mesh
                  geometry={nodes['������������_������_3_2_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_3_2_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
            </group>
          </group>
          <group position={[168.33, 207.96, -37.76]}>
            <group position={[18.24, 18.52, 0.36]} rotation={[-1.15, 0.22, -0.08]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_6_����������������1_0'].geometry}
                material={nodes['������������_������_6_����������������1_0'].material}
              />
            </group>
            <group position={[4.34, 17.82, 0]} rotation={[-1.14, -0.06, 0.03]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_5_Boy01_Hands_MAT_0'].geometry}
                material={nodes['������������_������_5_Boy01_Hands_MAT_0'].material}
              />
            </group>
            <group position={[6.61, -17.57, -0.04]} rotation={[-1.14, -0.06, 0.03]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_4_2_����������������3_0'].geometry}
                material={nodes['������������_������_4_2_����������������3_0'].material}
              />
            </group>
            <group position={[-4.89, -24.77, 0.16]} rotation={[-1.14, 0.08, -0.02]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_3_3_����������������2_0'].geometry}
                material={materials.material_20}
              />
            </group>
            <group position={[10.02, -0.41, 0.24]} rotation={[-1.07, 0.49, -0.17]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_2_3_����������������_0'].geometry}
                material={nodes['������������_������_2_3_����������������_0'].material}
              />
            </group>
            <group position={[5.5, 5.93, -0.03]} rotation={[-1.11, 0.24, -0.15]} scale={[0.27, 0.29, 0.01]}>
              <mesh
                geometry={nodes['������������_������_1_4_����������������3_0'].geometry}
                material={nodes['������������_������_1_4_����������������3_0'].material}
              />
            </group>
            <group position={[-39.81, 0.49, -0.69]} rotation={[-1.05, -0.19, 0.15]} scale={[0.78, 0.97, 0.04]}>
              <mesh
                geometry={nodes['������������_������_5_2_����������������_0'].geometry}
                material={nodes['������������_������_5_2_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[110.62, 160.63, 115.79]}>
            <group position={[-17.91, 90.85, 2.77]} rotation={[0.04, 0.14, 2.86]}>
              <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['����������_1_����������������_0'].geometry}
                  material={nodes['����������_1_����������������_0'].material}
                />
              </group>
              <group position={[0, 0, 0]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['����������_2_����������������_0'].geometry}
                  material={nodes['����������_2_����������������_0'].material}
                />
              </group>
              <mesh
                geometry={nodes['������������������������_1_����������������_0'].geometry}
                material={nodes['������������������������_1_����������������_0'].material}
              />
            </group>
            <group position={[17.91, -90.85, -2.77]} rotation={[0, 0, -0.23]}>
              <mesh
                geometry={nodes['����������_1_2_����������������_0'].geometry}
                material={nodes['����������_1_2_����������������_0'].material}
              />
              <mesh
                geometry={nodes['����������_2_2_����������������_0'].geometry}
                material={nodes['����������_2_2_����������������_0'].material}
              />
              <mesh
                geometry={nodes['������������������������_����������������_0'].geometry}
                material={nodes['������������������������_����������������_0'].material}
              />
            </group>
          </group>
          <group position={[0, -111.9, 0]}>
            <group position={[139.36, 164.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_3_4_����������������5_0'].geometry}
                material={nodes['������������_������_3_4_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 176.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_4_3_����������������5_0'].geometry}
                material={nodes['������������_������_4_3_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 188.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_5_3_����������������5_0'].geometry}
                material={nodes['������������_������_5_3_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 200.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_6_2_����������������5_0'].geometry}
                material={nodes['������������_������_6_2_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 212.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_7_����������������5_0'].geometry}
                material={nodes['������������_������_7_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 224.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_8_����������������5_0'].geometry}
                material={nodes['������������_������_8_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 236.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_9_����������������5_0'].geometry}
                material={nodes['������������_������_9_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 248.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_10_����������������5_0'].geometry}
                material={nodes['������������_������_10_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 260.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_11_����������������5_0'].geometry}
                material={nodes['������������_������_11_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 272.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_12_����������������5_0'].geometry}
                material={nodes['������������_������_12_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 284.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_13_����������������5_0'].geometry}
                material={nodes['������������_������_13_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 296.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_14_����������������5_0'].geometry}
                material={nodes['������������_������_14_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 308.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_15_����������������5_0'].geometry}
                material={nodes['������������_������_15_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 320.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_16_����������������5_0'].geometry}
                material={nodes['������������_������_16_����������������5_0'].material}
              />
            </group>
            <group position={[139.36, 332.36, -161.55]}>
              <mesh
                geometry={nodes['������������_������_17_����������������5_0'].geometry}
                material={nodes['������������_������_17_����������������5_0'].material}
              />
            </group>
          </group>
          <group position={[-30.05, 55.62, -158.16]} rotation={[0.04, -0.48, 0.02]}>
            <mesh
              geometry={nodes['Sweep_2_����������������5_0'].geometry}
              material={nodes['Sweep_2_����������������5_0'].material}
            />
          </group>
          <group position={[-3.28, 56.07, -160.14]} rotation={[0.04, -0.48, 0.02]}>
            <mesh
              geometry={nodes['Sweep_1_����������������5_0'].geometry}
              material={nodes['Sweep_1_����������������5_0'].material}
            />
          </group>
          <group position={[24.12, 56.46, -159.17]} rotation={[0.04, -0.48, 0.02]}>
            <mesh
              geometry={nodes['Sweep_����������������5_0'].geometry}
              material={nodes['Sweep_����������������5_0'].material}
            />
          </group>
          <group position={[139.63, 127.25, -102.1]}>
            <mesh
              geometry={nodes['������������_������_1_5_����������������5_0'].geometry}
              material={nodes['������������_������_1_5_����������������5_0'].material}
            />
          </group>
          <group position={[139.63, 127.25, -99.73]}>
            <mesh
              geometry={nodes['������������_������_1_6_����������������4_0'].geometry}
              material={nodes['������������_������_1_6_����������������4_0'].material}
            />
          </group>
          <group position={[140.75, 126.31, -52.15]}>
            <mesh
              geometry={nodes['������������_������_2_4__0'].geometry}
              material={nodes['������������_������_2_4__0'].material}
            />
          </group>
          <group position={[139.63, 164.59, -86.42]} rotation={[-1.58, 0, 0]}>
            <mesh
              geometry={nodes['������������_������_3_5__0'].geometry}
              material={nodes['������������_������_3_5__0'].material}
            />
          </group>
          <group position={[-31.47, 262.22, -92.77]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[88.61, 1.19, -21.41]} rotation={[-1.72, 1.53, -0.05]}>
              <mesh
                geometry={nodes['������������_��������������_14__0'].geometry}
                material={nodes['������������_��������������_14__0'].material}
              />
            </group>
            <group position={[26.08, 2.31, -47.81]} rotation={[-0.25, 0.99, -1.5]}>
              <mesh
                geometry={nodes['������������_��������������_5_2__0'].geometry}
                material={nodes['������������_��������������_5_2__0'].material}
              />
            </group>
            <group position={[-55.36, -4.03, -20.65]} rotation={[-1.72, 1.53, -0.05]}>
              <mesh
                geometry={nodes['������������_��������������_6_2__0'].geometry}
                material={nodes['������������_��������������_6_2__0'].material}
              />
            </group>
            <group position={[41.87, 17.89, -31.11]} rotation={[0, -0.58, 0]}>
              <mesh
                geometry={nodes['������������_������_6_4_����������������_0'].geometry}
                material={nodes['������������_������_6_4_����������������_0'].material}
              />
            </group>
            <group position={[111.8, 17.89, -14.8]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_7_2_����������������_0'].geometry}
                material={nodes['������������_������_7_2_����������������_0'].material}
              />
            </group>
            <group position={[-33.55, 17.89, -15.82]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_2_6_����������������_0'].geometry}
                material={nodes['������������_������_2_6_����������������_0'].material}
              />
            </group>
            <group position={[-31.09, -262.22, -92.9]} rotation={[Math.PI, 0, Math.PI]}>
              <group position={[-71.36, 281.21, -130.16]} rotation={[Math.PI, 0, Math.PI]}>
                <mesh
                  geometry={nodes['������������_������_1_7_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_7_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
              <group position={[-70.65, 280.11, -120.89]} rotation={[Math.PI, 0, Math.PI]}>
                <group position={[72.74, 0, 0]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_3_6_����������������_0'].geometry}
                    material={nodes['������������_������_3_6_����������������_0'].material}
                  />
                </group>
                <group position={[0.54, 0, 0]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_6_3_����������������_0'].geometry}
                    material={nodes['������������_������_6_3_����������������_0'].material}
                  />
                </group>
                <group position={[-73.28, 0, 0]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_2_5_����������������_0'].geometry}
                    material={nodes['������������_������_2_5_����������������_0'].material}
                  />
                </group>
              </group>
            </group>
          </group>
          <group position={[0.55, 15.5, -229.2]} rotation={[0.45, 0, 0]}>
            <group position={[0.08, 142.4, 0.02]} rotation={[-0.05, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_3__0'].geometry}
                material={nodes['������������_����������_3__0'].material}
              />
            </group>
            <group position={[0.1, 141.55, 0.05]} rotation={[-0.02, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_2_3__0'].geometry}
                material={nodes['������������_����������_2_3__0'].material}
              />
            </group>
            <group position={[0.1, 139.03, 0.1]} rotation={[-0.02, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_1_8__0'].geometry}
                material={nodes['������������_����������_1_8__0'].material}
              />
            </group>
            <group position={[-0.25, 158.34, -14.39]} rotation={[-0.45, 0, 0]}>
              <mesh
                geometry={nodes['������������_��������������_15__0'].geometry}
                material={nodes['������������_��������������_15__0'].material}
              />
            </group>
            <group position={[-0.55, 132.88, -1.68]} rotation={[-0.45, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_8__0'].geometry}
                material={nodes['������������_����������_8__0'].material}
              />
            </group>
            <group position={[0.65, 142.59, -1.83]} rotation={[2.07, 0, 0]}>
              <mesh
                geometry={nodes['������������_����������_3_0__0'].geometry}
                material={nodes['������������_����������_3_0__0'].material}
              />
            </group>
            <group position={[1.94, 142.59, 0.05]} rotation={[1.74, 0.47, 1.22]}>
              <mesh
                geometry={nodes['������������_����������_3_1__0'].geometry}
                material={nodes['������������_����������_3_1__0'].material}
              />
            </group>
            <group position={[0.55, 142.59, 1.86]} rotation={[1.16, 0.28, 2.57]}>
              <mesh
                geometry={nodes['������������_����������_3_2_2__0'].geometry}
                material={nodes['������������_����������_3_2_2__0'].material}
              />
            </group>
            <group position={[-1.6, 142.59, 1.1]} rotation={[1.16, -0.28, -2.57]}>
              <mesh
                geometry={nodes['������������_����������_3_3__0'].geometry}
                material={nodes['������������_����������_3_3__0'].material}
              />
            </group>
            <group position={[-1.54, 142.59, -1.18]} rotation={[1.74, -0.47, -1.22]}>
              <mesh
                geometry={nodes['������������_����������_3_4__0'].geometry}
                material={nodes['������������_����������_3_4__0'].material}
              />
            </group>
          </group>
          <group position={[-72.91, 106.07, -131.08]}>
            <mesh
              geometry={nodes['������������_������_8_2__0'].geometry}
              material={nodes['������������_������_8_2__0'].material}
            />
          </group>
          <group position={[-72.91, 137.4, -130.75]}>
            <mesh
              geometry={nodes['������������_������_1_8__0'].geometry}
              material={nodes['������������_������_1_8__0'].material}
            />
          </group>
          <group position={[-31.47, 55.26, -92.77]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[15.53, -2.4, -4.41]} rotation={[0, 0, 0]}>
              <group position={[-9.71, -40.45, -83.91]} rotation={[0, 0, 0]} scale={[0.44, 0.98, 1.12]}>
                <group position={[-6.74, 121.95, 113.02]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_6_5_Boy01_Shoes_MAT_1_0'].geometry}
                    material={nodes['������������_������_6_5_Boy01_Shoes_MAT_1_0'].material}
                  />
                </group>
                <group position={[10.9, 131.75, 111.24]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_7_3_Boy01_Shoes_MAT_1_0'].geometry}
                    material={nodes['������������_������_7_3_Boy01_Shoes_MAT_1_0'].material}
                  />
                </group>
              </group>
              <group position={[4.86, 19.05, 41.96]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_9_2_����������������_0'].geometry}
                  material={nodes['������������_������_9_2_����������������_0'].material}
                />
              </group>
              <group position={[4.86, 21.39, 41.96]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_1_9_Boy01_Hair_MAT_1_0'].geometry}
                  material={nodes['������������_������_1_9_Boy01_Hair_MAT_1_0'].material}
                />
              </group>
            </group>
            <group position={[113.58, -49.13, -6.35]} rotation={[Math.PI, -0.07, Math.PI]}>
              <mesh
                geometry={nodes['������������_������_4_4_Boy01_Shoes_MAT_1_0'].geometry}
                material={nodes['������������_������_4_4_Boy01_Shoes_MAT_1_0'].material}
              />
            </group>
            <group position={[112.64, -49.13, 83.02]} rotation={[Math.PI, -0.07, Math.PI]}>
              <mesh
                geometry={nodes['������������_������_2_7_Boy01_Shoes_MAT_1_0'].geometry}
                material={nodes['������������_������_2_7_Boy01_Shoes_MAT_1_0'].material}
              />
            </group>
            <group position={[-69.8, -49.13, 82.39]} rotation={[0, 0.07, 0]}>
              <mesh
                geometry={nodes['������������_������_3_7_Boy01_Shoes_MAT_1_0'].geometry}
                material={nodes['������������_������_3_7_Boy01_Shoes_MAT_1_0'].material}
              />
            </group>
            <group position={[-73.96, -49.13, -8.63]} rotation={[0, 0.07, 0]}>
              <mesh
                geometry={nodes['������������_������_5_4_Boy01_Shoes_MAT_1_0'].geometry}
                material={nodes['������������_������_5_4_Boy01_Shoes_MAT_1_0'].material}
              />
            </group>
            <group position={[46.73, 17.89, -15.82]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_6_6_����������������_0'].geometry}
                material={nodes['������������_������_6_6_����������������_0'].material}
              />
            </group>
            <group position={[-36.13, 52.01, -15.82]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_7_4_����������������_0'].geometry}
                material={nodes['������������_������_7_4_����������������_0'].material}
              />
            </group>
            <group position={[-36.68, 17.99, -15.82]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_8_3_����������������_0'].geometry}
                material={nodes['������������_������_8_3_����������������_0'].material}
              />
            </group>
            <group position={[-36.71, -16.55, -15.82]} rotation={[0, 0, 0]}>
              <mesh
                geometry={nodes['������������_������_9_3_����������������_0'].geometry}
                material={nodes['������������_������_9_3_����������������_0'].material}
              />
            </group>
            <group position={[75, 56.41, -19.62]} rotation={[0.77, 1.55, -2.35]}>
              <mesh
                geometry={nodes['������������_��������������_1_7__0'].geometry}
                material={nodes['������������_��������������_1_7__0'].material}
              />
            </group>
            <group position={[-36.31, 57.8, -21.04]} rotation={[0.77, 1.55, -2.35]}>
              <mesh
                geometry={nodes['������������_��������������_2_2__0'].geometry}
                material={nodes['������������_��������������_2_2__0'].material}
              />
            </group>
            <group position={[-36.72, 24.66, -21.04]} rotation={[0.77, 1.55, -2.35]}>
              <mesh
                geometry={nodes['������������_��������������_3_2__0'].geometry}
                material={nodes['������������_��������������_3_2__0'].material}
              />
            </group>
            <group position={[-37.17, -11.28, -21.04]} rotation={[0.77, 1.55, -2.35]}>
              <mesh
                geometry={nodes['������������_��������������_4_2__0'].geometry}
                material={nodes['������������_��������������_4_2__0'].material}
              />
            </group>
          </group>
          <group position={[-72.91, 112.32, -132.57]}>
            <mesh
              geometry={nodes['������������_������_10_2__0'].geometry}
              material={nodes['������������_������_10_2__0'].material}
            />
          </group>
          <group position={[282.36, 25.68, -8.24]}>
            <group position={[125.93, -21.4, -141.86]}>
              <group position={[-285.22, 26.62, 282.08]}>
                <mesh
                  geometry={nodes['������������_��������������_16_����������������3_0'].geometry}
                  material={nodes['������������_��������������_16_����������������3_0'].material}
                />
              </group>
              <group position={[-285.22, 27, 282.08]}>
                <mesh
                  geometry={nodes['������������_��������������_1_8_����������������3_0'].geometry}
                  material={nodes['������������_��������������_1_8_����������������3_0'].material}
                />
              </group>
            </group>
            <group position={[-157.72, 25.68, 114.42]}>
              <mesh
                geometry={nodes['������������_������_7_5_����������������3_0'].geometry}
                material={nodes['������������_������_7_5_����������������3_0'].material}
              />
            </group>
            <group position={[-158.94, 25.68, 165.28]}>
              <mesh
                geometry={nodes['������������_������_6_7_����������������3_0'].geometry}
                material={nodes['������������_������_6_7_����������������3_0'].material}
              />
            </group>
          </group>
          <group name="stol" position={[-51.75, 16.99, -131.51]} rotation={[Math.PI, 0, Math.PI]}>
            <group position={[73.85, 94.44, -70.58]} rotation={[-Math.PI, 0, 1.58]}>
              <mesh
                geometry={nodes['������������_��������������_17__0'].geometry}
                material={nodes['������������_��������������_17__0'].material}
              />
            </group>
            <group position={[132.17, -1.31, -50.77]} rotation={[Math.PI, 1.56, Math.PI]}>
              <group position={[54.35, 56.16, -54.64]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_6_9_����������������_0'].geometry}
                  material={nodes['������������_������_6_9_����������������_0'].material}
                />
              </group>
              <group position={[83.48, -16.99, -182.39]} rotation={[0, 1.55, 0]}>
                <group position={[-182.44, 73.08, -80.28]} rotation={[0, -1.55, 0]}>
                  <group position={[0, 1.17, 0]} rotation={[0, 0, 0]}>
                    <mesh
                      geometry={nodes['������������_������_1_10_Boy01_Hair_MAT_1_0'].geometry}
                      material={nodes['������������_������_1_10_Boy01_Hair_MAT_1_0'].material}
                    />
                  </group>
                  <group position={[0, -1.17, 0]} rotation={[0, 0, 0]}>
                    <mesh
                      geometry={nodes['������������_������_11_2_����������������_0'].geometry}
                      material={nodes['������������_������_11_2_����������������_0'].material}
                    />
                  </group>
                </group>
                <group position={[-151.32, 73.19, -25.94]} rotation={[0, -1.55, 0]}>
                  <mesh
                    geometry={nodes['del_����������������_0'].geometry}
                    material={nodes['del_����������������_0'].material}
                  />
                </group>
              </group>
              <group position={[4.69, -4.58, -128.99]} rotation={[0, 0, 0]} scale={[0.54, 0.99, 1.12]}>
                <group position={[-6.83, 121.95, 113.02]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_6_8_Boy01_Shoes_MAT_1_0'].geometry}
                    material={nodes['������������_������_6_8_Boy01_Shoes_MAT_1_0'].material}
                  />
                </group>
                <group position={[-6.88, 130.33, 108.92]} rotation={[0, 0, 0]}>
                  <mesh
                    geometry={nodes['������������_������_7_6_Boy01_Shoes_MAT_1_0'].geometry}
                    material={nodes['������������_������_7_6_Boy01_Shoes_MAT_1_0'].material}
                  />
                </group>
              </group>
              <group position={[93.46, -10.86, -45.17]} rotation={[-Math.PI, -0.07, Math.PI]}>
                <mesh
                  geometry={nodes['������������_������_4_5_Boy01_Shoes_MAT_1_0'].geometry}
                  material={nodes['������������_������_4_5_Boy01_Shoes_MAT_1_0'].material}
                />
              </group>
              <group position={[92.52, -10.86, 44.2]} rotation={[-Math.PI, -0.07, Math.PI]}>
                <mesh
                  geometry={nodes['������������_������_2_8_Boy01_Shoes_MAT_1_0'].geometry}
                  material={nodes['������������_������_2_8_Boy01_Shoes_MAT_1_0'].material}
                />
              </group>
              <group position={[-89.92, -10.86, 43.57]} rotation={[0, 0.07, 0]}>
                <mesh
                  geometry={nodes['������������_������_3_8_Boy01_Shoes_MAT_1_0'].geometry}
                  material={nodes['������������_������_3_8_Boy01_Shoes_MAT_1_0'].material}
                />
              </group>
              <group position={[-94.08, -10.86, -47.45]} rotation={[0, 0.07, 0]}>
                <mesh
                  geometry={nodes['������������_������_5_5_Boy01_Shoes_MAT_1_0'].geometry}
                  material={nodes['������������_������_5_5_Boy01_Shoes_MAT_1_0'].material}
                />
              </group>
              <group position={[-56.25, 90.28, -54.64]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_7_7_����������������_0'].geometry}
                  material={nodes['������������_������_7_7_����������������_0'].material}
                />
              </group>
              <group position={[-56.8, 56.26, -54.64]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_8_4_����������������_0'].geometry}
                  material={nodes['������������_������_8_4_����������������_0'].material}
                />
              </group>
              <group position={[-56.83, 21.71, -54.64]} rotation={[0, 0, 0]}>
                <mesh
                  geometry={nodes['������������_������_9_4_����������������_0'].geometry}
                  material={nodes['������������_������_9_4_����������������_0'].material}
                />
              </group>
            </group>
          </group>
          <group position={[0, 25.12, 0]} rotation={[Math.PI / 2, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[0, 471.74, 1307.9]} rotation={[0.77, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[1860.4, 189.72, 96.93]} rotation={[2.29, 0, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[330.45, 249.21, 418.41]} rotation={[1.37, 0, -0.63]}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group position={[-0.21, 29.15, -124.56]}>
            <primitive object={nodes._rootJoint} />
            <group position={[0.21, -29.15, -59.06]} />
            <skinnedMesh
              geometry={nodes.Boy01_Head_Geo_Boy01_Head_MAT_0.geometry}
              material={materials.Boy01_Head_MAT}
              skeleton={nodes.Boy01_Head_Geo_Boy01_Head_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_Hands_Geo_Boy01_Hands_MAT_0.geometry}
              material={materials.Boy01_Hands_MAT}
              skeleton={nodes.Boy01_Hands_Geo_Boy01_Hands_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_UpperBody_Geo_Boy01_UpperBody_MAT_0.geometry}
              material={materials.Boy01_UpperBody_MAT}
              skeleton={nodes.Boy01_UpperBody_Geo_Boy01_UpperBody_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_LowerBody_Geo_Boy01_LowerBody_MAT_0.geometry}
              material={materials.Boy01_LowerBody_MAT}
              skeleton={nodes.Boy01_LowerBody_Geo_Boy01_LowerBody_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_Shoes_Geo_Boy01_Shoes_MAT_0.geometry}
              material={materials.Boy01_Shoes_MAT}
              skeleton={nodes.Boy01_Shoes_Geo_Boy01_Shoes_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_Scarf_Geo_Boy01_Scarf_MAT_0.geometry}
              material={materials.Boy01_Scarf_MAT}
              skeleton={nodes.Boy01_Scarf_Geo_Boy01_Scarf_MAT_0.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Boy01_Hair_Geo_Boy01_Hair_MAT_0.geometry}
              material={materials.Boy01_Hair_MAT}
              skeleton={nodes.Boy01_Hair_Geo_Boy01_Hair_MAT_0.skeleton}
            />
          </group>
          <group scale={[1.22, 0.63, 1.1]}>
            <mesh
              geometry={nodes['������������_������_12_2_����������������_0'].geometry}
              material={nodes['������������_������_12_2_����������������_0'].material}
            />
            <group position={[0, 1.28, 0]}>
              <mesh
                geometry={nodes['������������_������_1_11_����������������1_0'].geometry}
                material={nodes['������������_������_1_11_����������������1_0'].material}
              />
            </group>
          </group>
          <group position={[30.78, 83.82, -36.38]}>
            <group position={[-180.76, 2666.86, 3745.5]} rotation={[-0.56, -0.86, 0.5]}>
              <group position={[-2706.86, 912.83, -3348.46]} rotation={[0, 0, 0]}>
                <group position={[42803.59, 133870.69, 73154.88]} rotation={[-1.07, 0.27, 0.46]}>
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]} />
                  </group>
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]} />
                  </group>
                </group>
                <group position={[-3256.74, -2044.13, -995.74]} rotation={[2.02, -0.96, 2.11]}>
                  <group rotation={[Math.PI / 2, 0, 0]}>
                    <group rotation={[Math.PI / 2, 0, 0]} />
                  </group>
                </group>
              </group>
              <group rotation={[Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
