/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: FLAREMEDIA (https://sketchfab.com/flaremedia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/6c18d8f196724f6f8438f53552af7a5f
title: Lowpoly  Tree 3
*/

import React, { useRef } from "react";
import PropTypes from "prop-types";
import { useGLTF } from "@react-three/drei";

import Tag from "./Tag";

function LongTree(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/longTree/scene.gltf");
  const { isEditMode } = props;

  return (
    <group ref={group} {...props} dispose={null} scale={[5, 5, 5]}>
      {isEditMode && <Tag position={[0, 20, 0]} args={[3, 0]} />}
      <mesh geometry={nodes.Tree_1_1_Tree_1_0.geometry} material={materials.Tree_1} />
      <mesh geometry={nodes.Tree_1_1_Mat3_0.geometry} material={materials["Mat.3"]} />
    </group>
  );
}

LongTree.propTypes = {
  isEditMode: PropTypes.bool.isRequired,
};

export default LongTree;

useGLTF.preload("models/longTree/scene.gltf");
