/* eslint-disable react/destructuring-assignment */
/* eslint-disable max-len */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mahdo (https://sketchfab.com/mahdo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/crossy-road-b7e2910d0ffe4da5860dedf39a7131d1
title: Crossy Road
*/

import React, { useEffect, useState } from "react";
import PropTypes from "prop-types";
import { useGLTF } from "@react-three/drei";

import Chicken from "./Chicken";
import SOCKET from "../../constants/socketEvents";
// TODO: prop types needed && get direction

function OtherUserAvatar({ user, socket }) {
  const [position, setPosition] = useState(user.position);
  const [direction, setDirection] = useState(user.direction);
  const { UPDATE_MOVEMENT } = SOCKET;

  useEffect(() => {
    socket.on(UPDATE_MOVEMENT(user.id), ({ newPosition, newDirection }) => {
      setPosition([...newPosition]);
      setDirection(newDirection);
    });
  }, [socket]);

  return (
    <Chicken
      position={[...position]}
      direction={direction}
      name={user.name}
    />
  );
}

OtherUserAvatar.propTypes = {
  user: PropTypes.object,
  socket: PropTypes.object,
};

export default OtherUserAvatar;

useGLTF.preload("models/chicken/scene.gltf");
