/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: joeantani (https://sketchfab.com/joeantani)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/cd5a7dc13ea8469e81a7908090e96b8e
title: LowPoly Tree
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/tree/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1266.04, 966.13, -13.75]} rotation={[-Math.PI, 0.02, 2.8]} />
          <group position={[24.5, 570.21, 0.02]}>
            <group position={[86.28, 156.82, 214.86]} rotation={[0, 1.36, 0]}>
              <mesh
                geometry={nodes.piccolo_1_Chiome_0.geometry}
                material={nodes.piccolo_1_Chiome_0.material}
              />
            </group>
            <group position={[150, 32.55, -214.83]} rotation={[0, -1.48, 0]}>
              <mesh
                geometry={nodes.piccolo_Chiome_0.geometry}
                material={nodes.piccolo_Chiome_0.material}
              />
            </group>
            <group position={[-211.78, 318.25, -0.02]} rotation={[0, 0.7, 0]}>
              <mesh
                geometry={nodes.piccolo2_Chiome_0.geometry}
                material={nodes.piccolo2_Chiome_0.material}
              />
            </group>
            <group position={[-24.5, -507.62, -0.02]}>
              <mesh geometry={nodes.Cylinder_Legno_0.geometry} material={materials.Legno} />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/tree/scene.gltf");
